### DISCUSSION TITLE
Even after assuming role with action, it is using EKS Worker node's role

### DISCUSSION THREAD

**Discussion by meetatmoe** [aws-actions/configure-aws-credentials#1058] [Q&A]
Hey, First question in community

here's part of my workflow file where I use action to assume the role

```
  build:
    needs: login-to-amazon-ecr
    runs-on: staging-ap-south-1
    container:
      image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/test/test-container:latest
      credentials:
        username: ${{ needs.login-to-amazon-ecr.outputs.docker_username }}
        password: ${{ needs.login-to-amazon-ecr.outputs.docker_password }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::xxxx:role/Github_OIDC
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: build image
        run: |
          cd ../ 
          docker run --rm public.ecr.aws/aws-cli/aws-cli sts get-caller-identity
          python /docker-image-builder.py

```
when I see the output of `sts get-caller-identity`  results into Worker node's IAM role. Is there something wrong with the workflow file?
