### DISCUSSION TITLE
Did the action support R2 of cloudflare ? if so how to setup the credentials ?

### DISCUSSION THREAD

**Discussion by eggcaker** [aws-actions/configure-aws-credentials#1294] [Q&A] [answered]
Did the action support R2 of cloudflare ? if so how to setup the credentials ?

**Comment by eggcaker** [comment]
i tried configure the access id and key with R2 keys , but it not working , got some error getaddrinfo ENOTFOUND sts.auto.amazonaws.com because the R2 need set the region to auto

**Reply by blatr** [reply, marked as answer]
@eggcaker I also haven’t figured out how to configure this action for R2, but you can simply use the AWS CLI with R2 by utilizing environment variables to set your access key and secret key directly i.e.
```
name: test r2 download

on:
  push:
    branches: [ master ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: auto

  build-and-push-artifacts:
    runs-on: ubuntu-latest

    steps:
     ...
     - name: Download Files from R2
        env:
          # Construct the R2 endpoint URL
          R2_ENDPOINT_URL: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          R2_BUCKET_NAME: test_bucket_name
        run: |
          echo "Downloading files from R2 bucket: $R2_BUCKET_NAME"
          mkdir -p ./artifacts

          aws s3 cp s3://$R2_BUCKET_NAME/ ./artifacts --recursive --endpoint-url $R2_ENDPOINT_URL

          echo "Listing downloaded files:"
          ls -lR ./artifacts


```
