### DISCUSSION TITLE
How do I use this action to assume root instead of assuming a role ?

### DISCUSSION THREAD

**Discussion by nitrocode** [aws-actions/configure-aws-credentials#1328] [Q&A]
At the moment, I'm doing this

```yaml
      - name: Get assume root creds
        id: assume
        env:
          TASK_POLICY: ${{ inputs.task_policy }}
          AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
        run: |
          # assume root
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
          $(aws sts assume-root \
            --target-principal "${{ env.AWS_ACCOUNT_ID }}" \
            --task-policy-arn "arn=arn:aws:iam::aws:policy/root-task/${{ env.TASK_POLICY }}" \
            --duration-seconds 900 \
            --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
            --output text))
```
