### DISCUSSION TITLE
Getting issue with id_token permissions

### DISCUSSION THREAD

**Discussion by scottdickerson** [aws-actions/configure-aws-credentials#561] [Q&A] [answered]
Here's our configuration for using the aws action taken from the documentation.  This was working for a long time:
```
deploy-to-stg:
    name: deploy-to-stg
    environment: stg
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
```

As of about 5 days ago we're getting
` The nested job 'deploy-to-stg' is requesting 'id-token: write', but is only allowed 'id-token: none'.`

As this says this is a nested workflow job, any ideas for updated configuration steps to fix this?
