### DISCUSSION TITLE
Helm can't reach cluster

### DISCUSSION THREAD

**Discussion by ovitor** [aws-actions/configure-aws-credentials#612] [General]
Hi everyone, 

We recently moved from `aws-access-key-id` and `aws-secret-access-key` to the `role-to-assume` option and since then I can no longer interact with the cluster.

I've followed the documentation provided on the page [GitHub's OIDC provider](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services).

```yaml
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: K8s Login
      run: aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CLUSTER }}
    
    - name: Test kubectl
      run: kubectl get pods -n default
```

More information:
* The step K8s Login works and I can see the `kubeconfig` file
* Other `aws` command like getting SSM parameter values works as well

Other tools that make use of the `kubeconfig` file don't work either, like helm for instance.

The error I'm facing is:

```
Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
```

Do you guys know what I'm doing wrong?
