### DISCUSSION TITLE
Can I pass authentication output to a reusable workflow?

### DISCUSSION THREAD

**Discussion by rdhar** [aws-actions/configure-aws-credentials#725] [Q&A]
Hi, thanks for sharing this super-handy action! 

#### Summary

I was looking to pass the output of AWS credential authentication from `caller.yml` job to a subsequent reusable `terraform.yml` workflow. 

This purpose serves to keep the reusable workflow as generic/un-opinionated as possible. It should use whatever environment variables output are passed in from the `caller.yml`, which might have different configure-aws-credentials steps.

#### Context

To ground this in something visual, here's an example of the `caller.tf` workflow:

```yml
jobs:
  authenticate:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::123456789012:role/terraform

  terraform:
    needs: authenticate
    uses: ./.github/workflows/terraform.yml
```

Since the "Authenticate AWS" step is present within the `authenticate` job, I'd like to pass its output to the reusable `terraform.yml` workflow in the `terraform` job so it can provision resources in accordance with the credentials provided in `caller.tf` workflow.

Please feel free to let me know if I can help provide any more information.
