### ISSUE TITLE
AWS_* credentials are persisted throughout the job steps 

### ISSUE THREAD

**Issue by 0mnius** [aws-actions/configure-aws-credentials#100]
Hello!

I can see that other actions in other steps are able to access **AWS_*** credentials set by `aws-actions/configure-aws-credentials@v1`:

![image](https://user-images.githubusercontent.com/42646186/88685226-6734b700-d0fe-11ea-80ab-da1b8f69b805.png)

Is there any flag like `persist-credentials: false` that i can use to unset those envars at the end of the step (like one in `actions/checkout`)?

Here is the workflow snips i use in my yaml file:

```yaml
jobs:
  myjob:
    runs-on: windows-2016
    steps:

      # Do some stuff

      # Setup AWS CLI credentials
    - name: 'Configure AWS creds'
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      # Publish to S3 
    - name: 'Copy to S3 bucket'
       run: |
         aws s3 cp ${{ github.workspace }}\foo\  s3://my-s3-bucket/bar/ --recursive --exclude "*" --include "*.baz"
       shell: pwsh

      # Send Slack notification
    - name: 'Slack channel notification'
       uses: 8398a7/action-slack@v3
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       # other slack action config
```

Thanks in advance!

**Comment by clareliguori** [comment]
Hi @0mnius can you clarify for your sample workflow when you would expect the env vars to get unset?
* After the `Configure AWS creds` step and before the `Copy to S3 bucket` step?
* After the `Copy to S3 bucket` step and before the `Slack channel notification` step?
* At the end of the `myjob` job?

**Comment by 0mnius** [comment]
Hi @clareliguori, thanks for a quick reply!

In my specific workflow i would either unite the aws steps and would expect the env vars to be unset after the `run` or at the end of the `Copy to S3 bucket` step:

```yaml
    - name: 'Copy to S3 bucket'
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
         persist-credentials: false
       run: |
         aws s3 cp ${{ github.workspace }}\foo\  s3://my-s3-bucket/bar/ --recursive --exclude "*" --include "*.baz"
       shell: pwsh
```

or probably as a separate step in the workflow:

```yaml
    - name: 'Configure AWS creds'
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

    - name: 'Copy to S3 bucket'
       run: |
         aws s3 cp ${{ github.workspace }}\foo\  s3://my-s3-bucket/bar/ --recursive --exclude "*" --include "*.baz"
       shell: pwsh

    - name: 'Unset AWS creds'
       uses: aws-actions/configure-aws-credentials@v1
       with:
         persist-credentials: false
```

I must admit that i'm still pretty new to the GH Actions world, so i hope this request does make sense in terms of the actions workflow design...

**Comment by clareliguori** [comment]
You can split your workflow into different jobs if you want a later step to have a "clean" environment.  I believe this is the expected way to use Actions.  Jobs do not share environment variables.  For example (note the `needs` field to establish the order of the jobs:
```
jobs:
  myjob:
    runs-on: windows-2016
    steps:
      # Setup AWS CLI credentials
    - name: 'Configure AWS creds'
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      # Publish to S3 
    - name: 'Copy to S3 bucket'
       run: |
         aws s3 cp ${{ github.workspace }}\foo\  s3://my-s3-bucket/bar/ --recursive --exclude "*" --include "*.baz"
       shell: pwsh

  notifyjob:
    runs-on: windows-2016
    needs: myjob
    steps:
      # Send Slack notification
    - name: 'Slack channel notification'
       uses: 8398a7/action-slack@v3
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       # other slack action config
```

**Comment by allisaurus** [comment]
@0mnius does the guidance [above](https://github.com/aws-actions/configure-aws-credentials/issues/100#issuecomment-665284658) make sense? We recently added an [explicit cleanup step](https://github.com/aws-actions/configure-aws-credentials/pull/101) post-job, but your workflow will still need to be broken up like this to see its effects.

**Comment by 0mnius** [comment]
@allisaurus, @clareliguori thank you for the suggestions, but isn't it a kind of a workaround to split and run on different runner? It makes the run a little bit longer ($). How complicated it to unset or maybe replace env vars with empty values? I tried this but couldn't actually make it work:

```yaml
      # Unset AWS env vars
    - name: 'unset AWS env vars'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: null
        aws-secret-access-key: null
        aws-region: us-east-1

    - name: 'list all env vars after unset'
      run: |
        gci env: | Format-Table -Wrap -AutoSize
      shell: pwsh

    - name: 'dump ENV context'
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
      run: echo "$ENV_CONTEXT"

      # test aws creds are actually unset
    - name: 'test aws creds'
      run: |
        aws s3 ls
      shell: pwsh
```
