### ISSUE TITLE
OIDC not working with `jobs.<job_id>.environment`

### ISSUE THREAD

**Issue by rkyuragi** [aws-actions/configure-aws-credentials#1024]
### Describe the bug

When specifying `jobs.<job_id>.environment` in the workflow, OIDC fails.

### Expected Behavior

It should be able to fetch credentials using a GitHub App token from a workflow under the GitHub repo that was setup in the Identity Provider on AWS side.

### Current Behavior

Executing the workflow results in the following error.

```
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Error: Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

![image](https://github.com/aws-actions/configure-aws-credentials/assets/115220685/181e0bf9-df7d-4871-a16b-d148c0f377a3)

### Reproduction Steps

This occurs when executing the following workflow.
Please configure the `role-to-assume` according to your environment.

```
name: CI/CD Workflow

on:
  push:
    branches:
      - test

jobs:
  set-env:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: develop
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-session-name: samplerolesession
          role-to-assume: 'arn:aws:iam::xxxx:role/xxxxx'
```

Commenting out the above `environment: develop` will result in success.
