### ISSUE TITLE
Proxy support does not work when moving from v2 to v4

### ISSUE THREAD

**Issue by RaviVadera** [aws-actions/configure-aws-credentials#1061]
### Describe the bug

We are using v2 behind a proxy. Proxy is setup through env vars and not explicitly on the action inputs. We are attempting to move to v4 because of deprecation of Node 16 actions and since Node 20 support is only available on v4. Proxy support on v4 does not work and fails with ```Error: connect ETIMEDOUT xxx.xxx.xxx.xxx:443```.

### Expected Behavior

Update to v4 should would without any changes to the action as I do not see that there is any breaking change from [changelog](https://github.com/aws-actions/configure-aws-credentials/blob/main/CHANGELOG.md).

### Current Behavior

Updating action from v2 to v4 fails with ```Error: connect ETIMEDOUT xxx.xxx.xxx.xxx:443```.

### Reproduction Steps

1. Use the v2 action behind a proxy, set the env vars in GH action, the action should be successful.
```yaml
env:
  http_proxy: xxxx
  https_proxy: xxxx
  no_proxy: xxxx

jobs:
  test:
    name: Test
    runs-on:
      group: xxxx
    environment:
      name: ${{ inputs.environment-name }}
    container:
      image: xxxx

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
```
2. Update the action by just changing the version to v4.
```diff
env:
  http_proxy: xxxx
  https_proxy: xxxx
  no_proxy: xxxx

jobs:
  test:
    name: Test
    runs-on:
      group: xxxx
    environment:
      name: ${{ inputs.environment-name }}
    container:
      image: xxxx

    steps:
      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
+        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
```

### Possible Solution

From the comment at https://github.com/aws-actions/configure-aws-credentials/issues/861#issuecomment-1730183352, it looks like there is a change in proxy implementation on v3 which can be the cause of failure. We tried updating from v2 to v3 and can confirm that proxy does not work even on v3.

**Comment by tim-finnigan** [comment]
Here is documentation on proxy configuration: https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#proxy-configuration

Have you tried using `http-proxy` as documented there? What error are you getting?

**Comment by RaviVadera** [comment]
@tim-finnigan all infromation included above already. But to reiterate,

We are relying on action to take the proxy from env (as indicated by documentation ```Additionally this action will always consider the HTTP_PROXY environment variable.```), so not configuring http-proxy explicitly.

As for the error,
> Proxy support on v4 does not work and fails with `Error: connect ETIMEDOUT xxx.xxx.xxx.xxx:443`.

**Comment by FelipeLopes-systematica** [comment]
Even passing http-proxy is not working...

**Comment by parm-p** [comment]
any news on this, this also seem impacted :(

**Comment by parm-p** [comment]
if I would do the PR on this, could it get reviewed and merged?

**Comment by ajto001** [comment]
Do you have any timeline to fix this bug?

**Comment by kellertk** [comment]
One thing I noticed here is you're setting the proxy via the environment. Support for that was dropped in the v3 rewrite; you now need to specify the proxy using an action input: https://github.com/aws-actions/configure-aws-credentials/blob/f503a1870408dcf2c35d5c2b8a68e69211042c7d/action.yml#L37-L39

In v2 we supported environment variables as well. https://github.com/aws-actions/configure-aws-credentials/blob/5fd3084fc36e372ff1fff382a39b10d03659f355/index.js#L280-L298

But in the latest releases we're only reading it from the action input https://github.com/aws-actions/configure-aws-credentials/blob/b47578312673ae6fa5b5096b330d9fbac3d116df/src/index.ts#L49

---

That said, in the current version I am able to get an HTTP proxy to work by using the action input. I've done this with my local machine, so there's some oddness around setting up the environment, but I set up a local proxy with `mitmproxy` on port 8080 and got this to fetch credentials from my testing account
```
env \
INPUT_AWS\-ACCESS\-KEY\-ID="${AWS_ACCESS_KEY_ID}" \
INPUT_AWS\-REGION="us-west-2" \
INPUT_AWS\-SECRET\-ACCESS\-KEY="${AWS_SECRET_ACCESS_KEY}" \
INPUT_AWS\-SESSION\-TOKEN="${AWS_SESSION_TOKEN}" \
INPUT_ROLE\-TO\-ASSUME="arn:aws:iam::570774169190:role/Admin" \
INPUT_DISABLE\-RETRY="true" \
GITHUB_REPOSITORY="foo/foo" \
GITHUB_WORKFLOW="fakeworkflow" \
GITHUB_ACTION="fakeaction" \
GITHUB_ACTOR="kellertk" \
GITHUB_SHA="fakesha" \
GITHUB_WORKSPACE="fakeworkspace" \
INPUT_HTTP\-PROXY="http://127.0.0.1:8080" \
NODE_TLS_REJECT_UNAUTHORIZED="0" \
node dist/index.js
```

Note the format of the proxy input: it needs to be what https://www.npmjs.com/package/https-proxy-agent (what we've been using for proxy support since at least v2) expects. Could you check that you're using the action input to specify the HTTP proxy? Like

```
jobs:
  test:
    name: Test
    runs-on:
      group: xxxx
    environment:
      name: ${{ inputs.environment-name }}
    container:
      image: xxxx

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          http-proxy: xxx
```
