### ISSUE TITLE
OIDC: Can't assume role containing "github"

### ISSUE THREAD

**Issue by bbergeron0** [aws-actions/configure-aws-credentials#1093]
### Describe the bug

Just like #953, OIDC seems to break down when the IAM role contains "GitHub." The runner couldn't assume the role of "github-action-deploy-to-staging" or "test-github-cicd," but assumed the role of "deploy-to-staging" without a hic, with the only difference between these roles being their name. After finding the aforementioned issue, I gave the solution a try and it worked.

### Expected Behavior

I expect it to work even if the role contains "github".

### Current Behavior

In GH action logs:

```
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
...
Assuming role with OIDC
Error: Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

### Reproduction Steps

As I said, the role must contains "github" to fail. Here's the failing step in question; (Also, permissions.id-token = write)

```
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::[redacted]:role/
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}
```

### Possible Solution

#954 suggested to "either highlighting this restricted role name in the documentation, or fixing the issue preventing use of this role name." I'd like to vote for the second option this time around ;)

**Comment by gyfchong** [comment]
Mine doesn't seem to work even without `github` in the role name 😢 

Github action: https://github.com/gyfchong/rumblr/blob/f66285185f64529004668a8d14878bcbac4d16a6/.github/workflows/deployment.yml#L28

Failed action:
https://github.com/gyfchong/rumblr/actions/runs/9625696385/job/26550841968#step:4:24

**Comment by tim-finnigan** [comment]
This note was added to the [README](https://github.com/aws-actions/configure-aws-credentials/blob/main/README.md#oidc):
>Note: Naming your role "GitHubActions" has been reported to not work. See https://github.com/aws-actions/configure-aws-credentials/issues/953.

More investigation is needed into why a role containing "github" doesn't work and what could be done about it.

**Comment by sambarfoot** [comment]
@tim-finnigan I'm faced with the same issue today. This worked last week but today failed.  

Below show the successful job last week. 
```
Run aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: arn:aws:iam::119075577[3](https://github.com/XXXXX/backend/actions/runs/XXXXX/job/XXXXX#step:3:3)57:role/Github_Action_Role
    aws-region: eu-west-1
    audience: sts.amazonaws.com
Assuming role with OIDC
Authenticated as assumedRoleId XXXXXX[6](https://github.com/XXXXXX/backend/actions/runs/XXXXX/job/XXXXX#step:3:7)XXXX:GitHubActions
```

This is the error in AWS Cloud Trial
```
"errorCode": "AccessDenied",
    "errorMessage": "An unknown error occurred",
    "requestParameters": {
        "roleArn": "arn:aws:iam::XXXXXXX:role/Github_Action_Role",
        "roleSessionName": "GitHubActions",
        "durationSeconds": 3600
    },
```

Is it possible something has changed in AWS?

**Comment by kuber-** [comment]
Had the same issue. Issue being - if the assumed role name is (in our case, it was exact match) GitHub, it fails as originally reported. Renaming the role (for example, changing to gh-oidc-role) with no other changes works. A couple of interesting things, 
1. We have 3 AWS accounts and only 2 out of 3 have this issue. The third has a role name exactly GitHub and it works! 
2. All three with role name GitHub were working for many months and aforementioned two stopped working around 31 july 2024! 

For reference, action is invoked as follows, 

```
uses: aws-actions/configure-aws-credentials@v4.0.2
with:
  role-to-assume: arn:aws:iam::xxxx:role/GitHub
  role-session-name: GitHub_to_AWS_via_FederatedOIDC
```
