### ISSUE TITLE
Getting aws command not found on MacOS self-hosted runner

### ISSUE THREAD

**Issue by dskvr** [aws-actions/configure-aws-credentials#113]
Generally, this action appears to expose the `aws` cli to subsequent actions, however, on a self-hosted MacOS runner I get the following error:

```
/Users/runner/actions-runner/_work/_temp/***.sh: line 1: aws: command not found
```

With config:
```
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Upload Artifacts to Primitive S3 Artifacts Manager
        run: |
          aws configure set default.s3.multipart_threshold 300MB
```

Exact same logic passes on `ubuntu-latest` github-hosted runner. Looking at documentation, it is suggested that self-hosted runners do not actually require any additional setup, docs only mention the convenience of not passing around secrets. However, this does not actually appear to be the case. 

~Installing AWS CLI manually on runner had no affect.~ Installed with sudo, and it worked. 

`README.md` should be updated to reflect this requirement.
