### ISSUE TITLE
Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by kaykhan** [aws-actions/configure-aws-credentials#1137]
### Describe the bug

Fails to assume role with OIDC.

### Expected Behavior

Expect to assume the role

### Current Behavior

```
Run aws-actions/configure-aws-credentials@v4
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Error: Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

### Reproduction Steps

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<ACOUNT_ID>:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:sub": "repo:<ORG>/*",
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

```
permissions:
  id-token: write
  contents: read
  ...
      - name: Checkout
        uses: actions/checkout@master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<account_id>:role/<org>-gh-actions-role
          role-session-name: cdk
          aws-region: ${{ env.AWS_REGION }}
 ```

**Comment by JulienAdaly** [comment]
Faced the same bug when using environment-level secrets in a job (e.g. below)

```
...

jobs:

  do-something:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment: production

    steps:
    - uses: actions/checkout@v4
 
   ...

```

When I remove the associated line (i.e. `environment: production`) it works fine.
