### ISSUE TITLE
set-output in gha is deprecated

### ISSUE THREAD

**Issue by reisraff** [aws-actions/configure-aws-credentials#1145]
### Describe the bug

Sonner GHA will deprecate the "set-output" feature. 

Reference: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Expected Behavior

do not show deprecation warning

### Current Behavior

showing:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### Reproduction Steps

```yaml
- name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
```

### Possible Solution

```
run: |
  echo "VAR=${value}" >> $GITHUB_ENV
```

### Additional Information/Context

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#environment-files

**Comment by kellertk** [comment]
aws-actions/amazon-ecr-login is not this repository. Did you mean to open this issue there?

**Comment by reisraff** [comment]
Oh... sorry... I wrote the description by copying and pasting.

Actially it is yes the configure-aws-credentials, take a look:

![image](https://github.com/user-attachments/assets/311ad1f3-c556-45a1-9e8c-ae6512bb5ebc)

Updating the way to reproduce:

```yml
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
```
