### ISSUE TITLE
HTTP_PROXY environment variable is ignored

### ISSUE THREAD

**Issue by Titzi90** [aws-actions/configure-aws-credentials#1165]
### Describe the bug

According to your Documentation the action should concider the `HTTP_PROXY` environment variable:
> Additionally this action will always consider the HTTP_PROXY environment variable.

However it seems it does not. 

Running the following workflow behind a proxy does not work:
```
name: Proxy Test
on: workflow_dispatch
jobs:
  test:
    runs-on: self-hosted
    permissions:
      id-token: write   # This is required for requesting the JWT from awsG
      contents: read    # This is required for actions/checkout
    steps:
      - name: set proxy
        run: |
          echo "HTTP_PROXY=http://my-proxy.com" >> $GITHUB_ENV
          echo "HTTPS_PROXY=http://my-proxy.com" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::1234567890
          aws-region: eu-west-1
```

while this action where the proxy is explicit set does work:
```
name: Proxy Test
on: workflow_dispatch
jobs:
  test:
    runs-on: self-hosted
    permissions:
      id-token: write   # This is required for requesting the JWT from awsG
      contents: read    # This is required for actions/checkout
    steps:
      - name: set proxy
        run: |
          echo "HTTP_PROXY=http://my-proxy.com" >> $GITHUB_ENV
          echo "HTTPS_PROXY=http://my-proxy.com" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::1234567890
          aws-region: eu-west-1
          http-proxy: ${{ env.HTTP_PROXY }}
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Example one to work as example two

### Current Behavior

Example one fails to connect to aws (time out)

### Reproduction Steps

see above

**Comment by Titzi90** [comment]
I tested a few older versions of `aws-actions/configure-aws-credentials`.
It looks like it does work with v2 but stop working in v3:
```
name: Proxy Test
on: workflow_dispatch
jobs:
  test:
    runs-on: self-hosted
    permissions:
      id-token: write   # This is required for requesting the JWT from awsG
      contents: read    # This is required for actions/checkout
    steps:
      - name: set proxy
        run: |
          echo "HTTP_PROXY=http://my-proxy.com" >> $GITHUB_ENV
          echo "HTTPS_PROXY=http://my-proxy.com" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::1234567890
          aws-region: eu-west-1
```
runs as expected and gives the following message:
```
Setting proxy from environment: http://my-proxy.com/
```
