### ISSUE TITLE
Key is only valid for 60 seconds

### ISSUE THREAD

**Issue by henrygriffiths** [aws-actions/configure-aws-credentials#1183]
### Describe the bug

I am using the credentials to copy a series of files with multiple scp commands. The files are able to be copied for the first 60 seconds, and then the commands fail with the output
```
REDACTED@REDACTED.compute.amazonaws.com: Permission denied (publickey).
lost connection
```

From the auth.log:
```
AuthorizedKeysCommand /usr/share/ec2-instance-connect/eic_run_authorized_keys ubuntu SHA256:REDACTED failed, status 255
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The authorization is valid for the period specified in `role-duration-seconds`.

### Current Behavior

The authorization is valid for 60 seconds.

### Reproduction Steps

I am using the following action variables and steps to create and copy over the SSH key:

```yaml
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role
        aws-region: ${{ env.AWS_REGION }}
        role-duration-seconds: 3600

    - name: Copy SSH Key
      run: |
        ssh-keygen -t rsa -f gha_temp_key -V +1h -N ""
        aws ec2-instance-connect send-ssh-public-key --region ${{ env.AWS_REGION }} --instance-id ${{ env.EC2_ID }} --availability-zone ${{ env.AWS_REGIONAZ }} --instance-os-user REDACTED --ssh-public-key file://gha_temp_key.pub
```

### Additional Information/Context

By evaluating the `timestamp` and `curtime` variables in `/usr/share/ec2-instance-connect/eic_parse_authorized_keys` on the ec2 instance, I can see that the key is only valid for ~60 seconds, and that requests fail when the expression result changes. Commenting out the `[ "${timestamp}" -gt "${curtime}" ]` evaluation allows the key to continue to be valid and all files to be scp'd over.
