### ISSUE TITLE
CDK deployment implicit cross-account role-chaining no longer works with initial OIDC role assumption

### ISSUE THREAD

**Issue by linbasil** [aws-actions/configure-aws-credentials#1189]
### Describe the bug

The CDK implicit cross-account role-chaining for multi-account CDK deployments no longer works correctly with configure-aws-credentials. In this deployment topology, a single hub account serves as the primary deployment role provider, and `sts:AssumeRole` permissions are applied to this role to allow for CDK role assumptions in spoke deployment accounts. Spoke account CDK roles are modified to trust the hub role.

When deploying with this topology via GitHub Actions using configure-aws-credentials, we no longer have the automatic ability to perform role-chaining by allowing the hub account role to assume spoke account CDK deployment roles. The issue was first discovered around 9:13AM PDT on Oct 22, 2024, and was working as of Oct 21, 2024. This issue is both present in `aws-actions/configure-aws-credentials@v1-node16` and `aws-actions/configure-aws-credentials@v4`, the two tested versions.

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

When using `aws-actions/configure-aws-credentials@v1-node16`, I expect GitHub Actions to assume the hub account deployment role. When deploying CDK code through a `cdk deploy --all --require-approval never` bash command on the GitHub-hosted Ubuntu-latest runner, I expect CDK to automatically use role-chaining to assume spoke deployment account CDK roles. CDK deployment will then proceed successfully.

### Current Behavior

When using `aws-actions/configure-aws-credentials@v1-node16` or `aws-actions/configure-aws-credentials@v4`, the hub account deployment role is successfully assumed via OIDC. However, role-chaining will fail with the following error message: `Need to perform AWS calls for account [SPOKE ACCOUNT], but the current credentials are for [HUB ACCOUNT]`. The same behavior and role-chaining work correctly within a local bash shell, but not within GitHub Actions.

### Reproduction Steps

The following composite action steps are used:

```yaml
- name: Assume tools account IAM role using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.githubActionsRoleArn }}
        aws-region: ${{ env.AWS_REGION }}
        role-duration-seconds: 28800

- name: Deploy CDK infrastructure
      working-directory: ${{ github.workspace }}/${{ inputs.cdkProjectRoot }}
      shell: bash
      run: cdk deploy --all --require-approval never
```

When running the given composite action, initial OIDC role assumption to the hub account will work correctly, but any implicit role-chaining required by CDK to perform CDK calls to spoke accounts fails with `Need to perform AWS calls for account [SPOKE ACCOUNT], but the current credentials are for [HUB ACCOUNT]`.
