### ISSUE TITLE
Can’t configure credentials with GitHub App

### ISSUE THREAD

**Issue by slocoro** [aws-actions/configure-aws-credentials#1257]
### Describe the bug

I have a python script that triggers a Github Actions workflow using a Github App installation. The triggered workflow fails with the following message when trying to configure AWS credentials:

```
Error: Could not assume role with web identity token file: Unable to validate tags
```

Weirdly, when I use a PAT instead of the Github App installation I'm able to configure the credentials.

Found this similar looking issue https://github.com/aws-actions/configure-aws-credentials/issues/930 but wasn't able to solve my problem.

Any help will be greatly appreciated :)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The action is able to configure the credentials without failing.

### Current Behavior

The action fails with this error:

```
Error: Could not assume role with web identity token file: Unable to validate tags
```

### Reproduction Steps

Use a Github App installation to trigger the workflow using Github's [create workflow dispatch API](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event)

```
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
    steps:
      - name: Configure AWS credentials
        uses: github-actions/configure-aws-credentials@v4
        with:
          aws-region: <my-region>
          role-to-assume: <my-role>
          role-session-name: <my-session-name>

```
