### ISSUE TITLE
4.1.0 - Value `dependabot[bot]` at `roleSessionName` failed to satisfy constraint

### ISSUE THREAD

**Issue by zbigniew-malcherczyk-tg** [aws-actions/configure-aws-credentials#1306]
### Describe the bug

```
Could not assume role with OIDC: 1 validation error detected: Value 'dependabot[bot]' at 'roleSessionName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]*
```

Seems like with `aws-actions/configure-aws-credentials@v4.1.0` dependabot now as an actor does not possess the validation pattern.

```
with:
    role-to-assume: (deducted)
    aws-region: eu-west-1
    role-session-name: dependabot[bot]
    audience: sts.amazonaws.com
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

-

### Current Behavior

-

### Reproduction Steps

-
