### ISSUE TITLE
Incorrect Audience token error when configuring aws credentials in github deploy pipeline

### ISSUE THREAD

**Issue by esparter** [aws-actions/configure-aws-credentials#1309]
### Describe the bug

With following Github action build file

```yaml
on:
  push:
    branches:
      - develop
    paths:
      - "packages/**"

env:
  BRANCH_NAME: ${{ github.ref_name }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and deploy UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GithubEstimatorRole
          role-session-name: estimator-deploy-session
          aws-region: eu-west-1
```

Role is defined in AWS. I copied role ARN from IAM console
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::123456789012:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:sub": "repo:*********/estimator:ref:refs/heads/develop",
                    "token.actions.githubusercontent.com:aud": "sts.amazonws.com"
                }
            }
        }
    ]
}
```

The identity provider is also set up on the AWS console with name `token.actions.githubusercontent.com` and an audience of  `sts.amazonws.com`

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The assume role to succeed

### Current Behavior

I see the following error:

```
Run aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: arn:aws:iam::123456789012:role/GithubEstimatorRole
    role-session-name: estimator-deploy-session
    aws-region: eu-west-1
    audience: sts.amazonaws.com
  env:
    BRANCH_NAME: develop
Assuming role with OIDC
Assuming role with OIDC
...
Assuming role with OIDC
Error: Could not assume role with OIDC: Incorrect token audience
```

### Reproduction Steps

Difficult to repro in code as it involves setting up in AWS console

### Additional Information/Context

Running github/actions-oidc-debugger@main produces

```
{
  "actor": "*********",
  "actor_id": "1702747",
  "aud": "https://github.com/**********",
  "base_ref": "",
  "event_name": "push",
  "exp": 1742320077,
  "head_ref": "",
  "iat": 174229477,
  "iss": "https://token.actions.githubusercontent.com",
  "job_workflow_ref": "********/estimator/.github/workflows/build-deploy-ui-minimal.yml@refs/heads/develop",
  "job_workflow_sha": "bc24b5d73d7c4237a1ef34abad8231f78f06cfb",
  "jti": "61c129b9-1ff1-440c-bc45-83f1951f79c4",
  "nbf": 1742298177,
  "ref": "refs/heads/develop",
  "ref_protected": "false",
  "ref_type": "branch",
  "repository": "********estimator",
  "repository_id": "948480860",
  "repository_owner": "********",
  "repository_owner_id": "203284062",
  "repository_visibility": "private",
  "run_attempt": "1",
  "run_id": "922424665",
  "run_number": "2",
  "runner_environment": "github-hosted",
  "sha": "bc24b5d73d7c94237a1ef34abad8231f78f06cfb",
  "sub": "repo:*********/estimator:ref:refs/heads/develop",
  "workflow": "Deploy UI",
  "workflow_ref": "********/estimator/.github/workflows/build-deploy-ui-minimal.yml@refs/heads/develop",
  "workflow_sha": "bc24b5d73d7c94237a1ef34abad81f78f06cfb"
}
```
