### ISSUE TITLE
Error performing any action on GitHub Actions: "The security token included in the request is invalid"

### ISSUE THREAD

**Issue by jdrydn** [aws-actions/configure-aws-credentials#131]
Hi there, apologise for such a basic issue - been banging my head against the desk for far too long on this 😬 

Attempting to get this working with GitHub Actions (GitHub-hosted runner) and I can't seem to get this to work at all:

```yml
name: CICD
on:
  - push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
```

Always results in:
```
> Run aws-actions/configure-aws-credentials@v1
##[error]The security token included in the request is invalid.
(node:2546) UnhandledPromiseRejectionWarning: InvalidClientTokenId: The security token included in the request is invalid.
    at Request.extractError (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:2473:29)
    at Request.callListeners (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:30526:20)
    at Request.emit (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:30498:10)
    at Request.emit (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:8502:14)
    at Request.transition (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:7836:10)
    at AcceptorStateMachine.runTo (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:15674:12)
    at /home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:15686:10
    at Request.<anonymous> (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:7852:9)
    at Request.<anonymous> (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:8504:12)
    at Request.callListeners (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1/dist/index.js:30536:18)
(node:2546) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2546) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So, for sanity's sake I added this in just before configure-aws-credentials:

```yml
steps:
  - run: aws sts get-caller-identity
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2
```

Which always returns:

```
> Run aws sts get-caller-identity

An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
##[error]Process completed with exit code 255.
```

I can confirm the credentials work on my Mac - `aws sts get-caller-identity` returns a JSON block with the `UserId`, `Account` & user's `Arn`. These are user credentials with the following permissions:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "sts:GetCallerIdentity",
            "Resource": "*"
        }
    ]
}
```

(I also temporarily gave it Administrator permissions yesterday to confirm it wasn't a permissions issue, to no effect)

The secrets are organisation-wide & I am certain are being pulled through - another secret I have is a `SLACK_WEBHOOK_URL` which is used to report that the builds fail (because of the error mentioned above!).

Is there any additional setup required with GitHub Actions to get this to work out-of-the-box that I'm missing?

Thanks,
