### ISSUE TITLE
Configure inputs with environment variables

### ISSUE THREAD

**Issue by pemattr** [aws-actions/configure-aws-credentials#1335]
### Describe the feature

I'd like the ability to define the default parameters for the action through environment variables. This was I can have my role arn and region configured within the environment on Github and i can simplify the experience for my developers.

### Use Case

This allows a simpler way the enable developers to use this action if the environment variables are defined at the repo or org level.

### Proposed Solution

```
jobs:
  check:
    name: Test
    env:
      AWS_REGION: eu-west-2
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4.1.0
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change
