### ISSUE TITLE
Wrong example region for China partition

### ISSUE THREAD

**Issue by jizusun** [aws-actions/configure-aws-credentials#1386]
### Describe the issue

https://github.com/aws-actions/configure-aws-credentials/blob/main/README.md#oidc-audience

```
    - name: Configure AWS Credentials for China region audience
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        audience: sts.amazonaws.com.cn
        aws-region: us-east-3
        role-to-assume: arn:aws-cn:iam::123456789100:role/my-github-actions-role
```

I guess the `aws-region` should be something like `cn-northwest-1`.
