### ISSUE TITLE
Could not load credentials from any providers

### ISSUE THREAD

**Issue by marcus-vw** [aws-actions/configure-aws-credentials#202]
We use Github Workflows for several projects. Some of them won't work with the `configure-aws-credentials` action. The workflow gets triggered and fails during the `configure-aws-credentials` action with the following error message: `Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers`. It works if I restart the workflow manually.

Most of the Github workflows are triggered due to a Dependabot created PR. What drives me nuts is that it works for some Github Workflows but for other it never works (just by manually rerunning the workflow).

An example workflow looks like this
```
name: Pull Request

on:
  pull_request:
    branches: 
      - master
    types: [opened, synchronize, reopened]

jobs:        
  build:
    name: My Fancy Build Job

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --prefer-offline --frozen-lockfile
      
      - name: ESLint
        run: yarn lint

      - name: Test
        run: yarn test
```

The corresponding `dependabot.yml` could look like this
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "aws-cdk"
      - dependency-name: "@aws-cdk/*"
    reviewers:
      - "steffen"
```
