### ISSUE TITLE
[Error at /MyStack] Need to perform AWS calls for account ***, but no credentials have been configured

### ISSUE THREAD

**Issue by jgcmarins** [aws-actions/configure-aws-credentials#228]
Hi everyone! Thanks for this amazing GH action. I have been using it almost over the past 2 years and it's being great!

I have a repository that was inactive for almost one year. Last weekend I tried to upgrade some dependencies and after merging to the `main` branch, I got an error in the deploy step with AWS CDK:

`[Error at /MyStack] Need to perform AWS calls for account ***, but no credentials have been configured`

Here's my GitHub Action file:
```yml
name: Server Deploy on staging

on:
  push:
    branches:
      - main

jobs:
  # DEPLOY SERVER STAGING
  server-deploy-staging:
    name: Deploy Server on Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.17'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-east-1
      - name: Cache yarn.lock
        id: yarn-cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile --production=false --non-interactive
      - name: Deploy Server on Staging
        run: |
          cdk deploy MyStack \
            -c mode=staging \
            -c account='123' \
            --require-approval=never \
            --profile=my-profile
```

Any thoughts on why am I seeing this error?

The step `Configure AWS Credentials` is running successfully
<img width="431" alt="Screen Shot 2021-06-28 at 15 27 18" src="https://user-images.githubusercontent.com/5133450/123685748-6718cc00-d825-11eb-860e-46568de6227c.png">
