### ISSUE TITLE
When running on EC2 not picking up credentials

### ISSUE THREAD

**Issue by nitrocode** [aws-actions/configure-aws-credentials#245]
## context

I noticed that from a previous issue and subsequent pull request that this feature should be supported. I'm using the following yaml but it's not working as expected.

I'm on Amazon Linux 2 self-hosted EC2 instances.

I tried this

```yaml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
```

which returns `Error: Input required and not supplied: aws-region`

I tried this

```yaml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
```

which returns

```
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

## references
* @jwoltman's issue https://github.com/aws-actions/configure-aws-credentials/issues/33
* @clareliguori 's PR https://github.com/aws-actions/configure-aws-credentials/pull/42

similar issues in other projects
* https://github.com/docker/login-action/issues/64
* https://github.com/aws-actions/amazon-ecr-login/issues/174

**Comment by AmaniEzz** [comment]
I'm facing the same problem, have you found solutions?

**Comment by nitrocode** [comment]
@AmaniEzz @paragbhingre it looks like my issue was with setting the following input variables.

```yaml
    env:
      AWS_EC2_METADATA_DISABLED: true
      AWS_SDK_LOAD_CONFIG: true
```

My originaly issue was with using [docker/build-push-action](https://github.com/docker/build-push-action) which would throw errors because it couldn't read from the IAM role so I experiemented with running this action prior to the docker one and I ran into the same issue. I ended up not needing this action once I omitted the above env variables.

I have not re-tested the aws-actions/configure-aws-credentials after omitting the above env variables.
