### ISSUE TITLE
Branch name validation too strict

### ISSUE THREAD

**Issue by simonmumenthaler** [aws-actions/configure-aws-credentials#247]
We name our branches with a specific pattern that starts with a `#` followed by digits and other chars like `#2-bit-ref-r`.

But when executing the `configure-aws-credentials` action it fails since the name does not match the required regex pattern.

`1 validation error detected: Value 'refs/heads/#2-bit-ref-r' at 'tags.7.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*`

Since for github it's a valid branch name it should also be accepted by this action.

**Comment by dejwsz** [comment]
I have the same thing today for one of our branches

**Comment by dejwsz** [comment]
In our case such we had such error:
`Error: 1 validation error detected: Value 'refs/heads/CFA-94/Image_uploading_prototype_(company_logo)_' at 'tags.7.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*
`

**Comment by dejwsz** [comment]
After we changed the branch name it went through without any problems.

**Comment by paragbhingre** [comment]
@simonmumenthaler Thank you for reporting this issue with us. I tried reproducing this issue on my end and couldn't see the error that you are getting with the same branch name as yours i.e. `#2-bit-ref-r`
Could you please provide me some more information regarding this issue such as some screen shots, steps to reproduce, environment etc.

**Comment by simonmumenthaler** [comment]
@paragbhingre Thank you for investigating this problem.

I receive the the error in different repos. The action works when running on master but fails on our `#\d+-[a-z\d-]+` branches.

The config I use for the action:
```
name: Delete Orphan Stacks
on:
  schedule:
    - cron: '15 2 * * 1'
  workflow_dispatch: 
jobs:
  delete-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials for eu-central-1
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: 'arn:aws:iam::************:role/ScAccess'
          role-duration-seconds: 3600
          aws-region: eu-central-1
      - name: Delete Stacks in eu-central-1
        uses: shiftcode/delete-orphan-cfn-stacks-action@v0.0.6
        with:
          githubToken: ${{ secrets.GH_TOKEN_REPO_READ }}
          stackNamePrefix: 'pai-website'
          ignoreStacks: '["xx1"]'
```

Output when running on `#001-dev`:
![image](https://user-images.githubusercontent.com/37636934/129311110-f5f5639c-1b44-4757-82e1-fa2d18974f3c.png)
