### ISSUE TITLE
How to update the secert while running the actions?

### ISSUE THREAD

**Issue by LakshmiRavali** [aws-actions/configure-aws-credentials#255]
I am using this action to upload to s3, but my AWS_SECRET_ACCESS_KEY will expire after 30mins. I have a case where sometimes my script will take more than 30mins to execute and meanwhile this AWS_SECRET_ACCESS_KEY will expire. How to handle this kind of case?
For example:
```
steps:
      - uses: actions/checkout@master
      - run: bash script-run-more-time.sh # This might take more than 30mins
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-2
```
