### ISSUE TITLE
Using Instance Profile to Assume Role

### ISSUE THREAD

**Issue by peter-ro** [aws-actions/configure-aws-credentials#260]
Hi, I am trying to assume a role with an instance profile but it keeps saying that the token request is invalid. The instance is a Self-Hosted GitHub Runner that has the ability to assume a role (dev_terraform) within the AWS console but does not have full access to AWS.

Below is the permissions policy for the instance profile to assume the role (dev_terraform):

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "sts:AssumeRole",
                "sts:TagSession",
                "sts:GetFederationToken"
            ],
            "Resource": "dev_terraform"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "sts:GetSessionToken",
                "sts:GetAccessKeyInfo",
                "sts:GetCallerIdentity",
                "sts:GetServiceBearerToken"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "cloudformation:*",
            "Resource": "*"
        }
    ]
}
```

The permissions policy for the role that is being assumed (dev_terraform) has full admin access to the AWS environment. Below is the trust policy for the role that is being assumed (dev_terraform):

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "dev_github_runner"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}

```

Lastly, here is the github workflow I am trying to run:

```
name: Deploys CF from GH Runner

on:
  push:
    paths:
    - '.github/workflows/deployAwsCf.yml'

jobs:
  build:
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      GIT_SSL_NO_VERIFY: true
    runs-on: [aws-ubuntu-runner]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: dev_terraform
#        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
#        role-duration-seconds: 3600
#        role-session-name: CloudFormationSession
```

I have tried both this method and the role-to-assume method but neither of them work. I would like to know if I am missing anything else. I have tested the aws cli command on the virtual machine itself and it has worked successfully. Attached is the log file for the GitHub action.

[log_553.txt](https://github.com/aws-actions/configure-aws-credentials/files/7162715/log_553.txt)
