### ISSUE TITLE
Option to set "profile" for setting authenticatoin

### ISSUE THREAD

**Issue by srknc** [aws-actions/configure-aws-credentials#27]
Hi,
aws-actions/configure-aws-credentials@v1 by default generate credentials under default profile.
It would be nice to have a parameter to set `AWS_PROFILE` environment variable.

**Comment by clareliguori** [comment]
Tell me more: how are you using profiles in the GitHub Actions environment?  Do the non-default profiles have access key creds from other GitHub Actions secrets, or do they use role_arn?

**Comment by AutomationD** [comment]
Seems like I'm not able to use `default` profile either. @clareliguori Is the action supposed to create a default profile config?

**Comment by clareliguori** [comment]
No, this action only configures credentials as environment variables so that no credentials are written to disk in the GitHub Actions environment.  It does not configure profiles.

**Comment by AutomationD** [comment]
@clareliguori We're using aws profiles in our tooling, as we can't have only one single credential set. Things like `aws ecs --profile=profile-name ...`

**Comment by clareliguori** [comment]
Are those profiles role-based or do you have individual GitHub Action secrets that contain different access keys?

If you're able to break up the work into separate steps, the action can be repeated with different secrets:
```
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials for test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_ACCT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_ACCT_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to test account
      run: |
        aws ecs update-service ...

    - name: Configure AWS credentials for production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_ACCT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_ACCT_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to production account
      run: |
        aws ecs update-service ...
```
