### ISSUE TITLE
Could not load credentials from any providers

### ISSUE THREAD

**Issue by MatteoGioioso** [aws-actions/configure-aws-credentials#271]
I have already checked related issues #202 #188 , but in my case I am not using Dependabot.

This is my `pipeline.yaml` truncated till this action:

```
name: My Deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-1
          role-to-assume:arn:aws:iam::000000000000:role/github-actions-matteogioioso-saml-proxy
          role-session-name: GitHubActions
      
        ....

```

This is my trust relationship for that role:

```
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::000000000:oidc-provider/vstoken.actions.githubusercontent.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringLike": {
          "vstoken.actions.githubusercontent.com:sub": "repo:MatteoGioioso/saml-proxy:*"
        }
      }
    }
  ]
}
```

This is my OICD provider setup in IAM

![image](https://user-images.githubusercontent.com/43592430/135371310-7471b1bf-ca80-405b-b21b-ae0e9e4c35c4.png)

And this is the error:

```
Run aws-actions/configure-aws-credentials@v1
  with:
    aws-region: ap-southeast-1
    role-to-assume: arn:aws:iam::000000000000:role/github-actions-matteogioioso-saml-proxy
    role-session-name: GitHubActions
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

**I am not using a self-hosted runner**

What am I doing wrong? Maybe the audience?

Thanks

### UPDATE:

it seems like this method return false, because you do not validate credentials in the `assumeRole` method:

```
    const useGitHubOIDCProvider = () => {
        // The assumption here is that self-hosted runners won't be populating the `ACTIONS_ID_TOKEN_REQUEST_TOKEN`
        // environment variable and they won't be providing a web idenity token file or access key either.
        // V2 of the action might relax this a bit and create an explicit precedence for these so that customers
        // can provide as much info as they want and we will follow the established credential loading precedence.
        return roleToAssume && process.env.ACTIONS_ID_TOKEN_REQUEST_TOKEN && !accessKeyId && !webIdentityTokenFile
    }
```

honestly I cannot find a way to echo this variable `ACTIONS_ID_TOKEN_REQUEST_TOKEN`

### UPDATE 2:

ok, **this variable `ACTIONS_ID_TOKEN_REQUEST_TOKEN` is not set**, I am not sure why is not there and also I cannot find much information about it.

I am willing to submit a PR if needed.

**Comment by androidwiltron** [comment]
so i think there is an undocumented permissions thing you need to use in your workflow to get it

```
permissions:
  id-token: write
  contents: read
```

try that

**Comment by antondalgren** [comment]
I don't think a new release has been made since Jul 19 while OICD changes where merged two days ago. https://github.com/aws-actions/configure-aws-credentials/commit/b8c74de753fbcb4868bf2011fb2e15826ce973af

What happens if you change the version to master? `uses: aws-actions/configure-aws-credentials@v1`-> `uses: aws-actions/configure-aws-credentials@master`

**Comment by dyoshikawa** [comment]
I'm experiencing the exact same error too.

**Comment by richardhboyd** [comment]
I'm looking into this now. We used 'sigstore' in an earlier version while we were testing the action.

**Comment by richardhboyd** [comment]
I've been able to reproduce this. I'm working with the GitHub team to root cause it. Our plan was to use the audience `sts.amazonaws.com` since that indicates who you intend to hand the JWT to. It appears that the ability to set an arbitrary audience hasn't reached everywhere yet. I'm suggesting that we:

(1) roll this repo back to the version where the audience was hardcoded with `sigstore` for now

(2) I document in the repo's readme the additional permissions that are needed

(3) I add a note to teh readme that this feature is still undergoing changes by GitHub

Thoughts?

**Comment by MatteoGioioso** [comment]
@richardhboyd ok, I saw your last commit yesterday so I have tried using `aws-actions/configure-aws-credentials@master` and `sigstore` as audience and it is working

**Comment by MatteoGioioso** [comment]
I am not sure this is related to this action, but now I have the following error:

```
UnknownEndpoint: Inaccessible host: `api.ecr-public.ap-southeast-1.amazonaws.com' at port `undefined'. This service may not be available in the `ap-southeast-1' region
```

```
  - name: Run deployment script
    run: node pipeline.js
```

This is the shortened content of the script, is the point where it fails:

```
const AWS = require("aws-sdk");
const ecr = new AWS.ECRPUBLIC({
  region: process.env.AWS_REGION,
  apiVersion: '2020-10-30'
})

await ecr.getAuthorizationToken().promise();
```

I have tried by specifying the endpoint since `ecr-public` does not exit, but then I have this other error:

```
InternalFailure: null
    at Request.extractError (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InternalFailure',
  time: 2021-10-01T01:44:42.290Z,
  requestId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  statusCode: 500,
  retryable: true
}
```

**Comment by richardhboyd** [comment]
ecr-public is only available in us-east-1

**Comment by MatteoGioioso** [comment]
@MatteoGioioso oh, I see, thanks. It confused me because I have a repository in the Singapore region.

**Comment by richardhboyd** [comment]
a codecommit repository? the ecr-public registries are reachable from any region but you have to use the us-east-1 endpoint to retrieve your token to authenticate.

https://stackoverflow.com/questions/69274998/could-not-connect-to-the-endpoint-url-https-api-ecr-public-xxxxxxxxx-amazona

**Comment by MatteoGioioso** [comment]
ECR repository.

> reachable from any region but you have to use the us-east-1 endpoint 

I see, many thanks for the clarification

**Comment by dyoshikawa** [comment]
I solved the problem by doing the following.
Thank you.

https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931012696
https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931272443

**Comment by IMKnysh** [comment]
I tried to use ExternalId and got an error:
Error: Unexpected key 'ExternalId' found in params

Can I use ExternalId with OICD provider?

**Comment by richardhboyd** [comment]
no

**Comment by benkehoe** [comment]
You cannot use `ExternalId` with `AssumeRoleWithWebIdentity` ([API docs](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html)). What may suffice is to have your trust policy conditioned on the "sub" claim, as shown here:
```json
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::000000000:oidc-provider/vstoken.actions.githubusercontent.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringLike": {
          "vstoken.actions.githubusercontent.com:sub": "repo:MatteoGioioso/saml-proxy:*"
        }
      }
    }
  ]
}
```
this claim is set by GitHub and cannot be changed by the user, so you can trust it to indicate the source. It's not quite the same as `ExternalId`; in particular, it doesn't fully solve [the confused deputy problem](https://research.nccgroup.com/2019/12/18/demystifying-aws-assumerole-and-stsexternalid/).

**Comment by ahawkins** [comment]
https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931805471 worked for me.

**Comment by davidkarlsen** [comment]
When will this feature be released (as it is implemented now on `master` branch? Are you waiting for github to go GA with their workload OIDC?

**Comment by ahawkins** [comment]
Seems there are more issues with `master`. I'm using a token like:

```
permissions:
  id-token: write
  contents: write
```

And an IAM provider like:

```
resource "aws_iam_openid_connect_provider" "github" {
	url             = "https://token.actions.githubusercontent.com"
	client_id_list  = [ "sigstore" ]
	thumbprint_list = [ "a031c46782e6e6c662c2c87c76da9aa62ccabd8e" ]
}

data "aws_iam_policy_document" "assume_role_policy" {
	statement {
		sid     = "GrantGithubActionsAccess"
		effect  = "Allow"
		actions = [ "sts:AssumeRoleWithWebIdentity" ]
		condition {
			test     = "StringLike"
			variable = "token.actions.githubusercontent.com:sub"
			values   = [ "repo:REDACTED:*" ]
		}
		principals {
			type        = "Federated"
			identifiers = [ aws_iam_openid_connect_provider.github.id ]
		}
	}
}
```

This was working a few days ago. Now it errors with `Incorrect token audience`. 

Has something changed in Github Actions itself?

**Comment by bryantbiggs** [comment]
@ahawkins change `client_id_list = [ "sigstore" ]` => to =>  `client_id_list = [ "sts.amazonaws.com" ]`

**Comment by tedivm** [comment]
If anyone needs it I wrote up a blog post on how to get it all working.

https://blog.tedivm.com/guides/2021/10/github-actions-push-to-aws-ecr-without-credentials-oidc/

**Comment by chris3ware** [comment]
> If anyone needs it I wrote up a blog post on how to get it all working.
> 
> https://blog.tedivm.com/guides/2021/10/github-actions-push-to-aws-ecr-without-credentials-oidc/

Thanks for the great write up of this functionality. One thing I have discovered from my implementation is that when using an ECR policy (resource based policy) which permits the IAM Federated user (in this case github actions), other IAM restrictions do not apply, as outlined in the policy evaluation logic described here [https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html](url)

**Comment by ohad-griiip** [comment]
After managing to define the OIDC and running my workflow I get - 
> Not authorized to perform sts:AssumeRoleWithWebIdentity

What am I missing? 🤔

**Comment by richardhboyd** [comment]
that usually means the condition on your IAM Role  is invorrect

**Comment by ohad-griiip** [comment]
> that usually means the condition on your IAM Role is invorrect

This is my IAM role - 
```yaml
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub githuboidc__${RepoName}
      MaxSessionDuration: 3600
      Policies:
        - PolicyName: inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRoleWithWebIdentity
                Resource:
                  - "*"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GithubOrg}/${RepoName}:*
```

**Comment by msandu62** [comment]
@ohad-griiip the issues is from the provider configuration. Make sure you have this at the audience: `sts.amazonaws.com`

**Comment by msandu62** [comment]
Maybe you are not using the right IAM role ARN on your github action workflow? Your config looks fine

**Comment by tedivm** [comment]
Can you confirm that `[deploy-role]` has the exact same name as what `!Sub githuboidc__${RepoName}` in your role definition turns into?

**Comment by ohad-griiip** [comment]
> Can you confirm that `[deploy-role]` has the exact same name as what `!Sub githuboidc__${RepoName}` in your role definition turns into?

@tedivm It doesn't - my goal is to authenticate via  github and then be able to assume a the actual role for the workflow

**Comment by tedivm** [comment]
That's not going to work. With OIDC connections you have to have a role as part of your initial connection. This is because that role is where permission is given permission to Github to hand out tokens. Without that permission you can't do anything.

> After you create an IAM OIDC identity provider, you must create one or more IAM roles. A role is an identity in AWS that doesn't have its own credentials (as a user does). But in this context, a role is dynamically assigned to a federated user that is authenticated by your organization's IdP. The role permits your organization's IdP to request temporary security credentials for access to AWS. 

One somewhat convoluted option would be to create a role with assume role permissions on other roles, so that one can be used to switch to the other, but I honestly can't see a good reason to do that. I'd just create a role for each repository and then assume it directly.

**Comment by ohad-griiip** [comment]
> That's not going to work. With OIDC connections you have to have a role as part of your initial connection. This is because that role is where permission is given permission to Github to hand out tokens. Without that permission you can't do anything.
> 
> > After you create an IAM OIDC identity provider, you must create one or more IAM roles. A role is an identity in AWS that doesn't have its own credentials (as a user does). But in this context, a role is dynamically assigned to a federated user that is authenticated by your organization's IdP. **The role permits your organization's IdP to request temporary security credentials for access to AWS.**
> 
> One somewhat convoluted option would be to create a role with assume role permissions on other roles, so that one can be used to switch to the other, but I honestly can't see a good reason to do that. I'd just create a role for each repository and then assume it directly.

Yep great it's working 🚀 thanks a lot @tedivm !

**Comment by danielcompton** [comment]
> When will this feature be released (as it is implemented now on `master` branch)? Are you waiting for github to go GA with their workload OIDC?

It looks like this was just released in v1.6.0: https://github.com/aws-actions/configure-aws-credentials/blob/v1.6.0/CHANGELOG.md#160-2021-11-23

**Comment by CallumHibbert** [comment]
Here is the official announcement: https://github.blog/2021-11-23-secure-deployments-openid-connect-github-actions-generally-available/

**Comment by kaihendry** [comment]
I'm hitting "Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers" whilst trying to follow https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions#examples

Do I need to set a secrets.AWS_ACCESS_KEY_ID / secrets.AWS_SECRET_ACCESS_KEY just to assume the role? I don't understand.

<img src="https://s.natalian.org/2022-01-08/test.png">

Here is my Github workflow: https://github.com/kaihendry/go-web-dynamo-starter/actions/runs/1670850055/workflow

I also posted upon https://github.community/t/aws-integration-2022/221472

Sidenote: Is it possible to setup a tag to limit the action to a certain stack to play it safe? https://s.natalian.org/2022-01-08/tags.png

**Comment by dyoshikawa** [comment]
@kaihendry 

Now, you should use `@v1` as stable version.

```diff
-     - uses: aws-actions/configure-aws-credentials@master
+     - uses: aws-actions/configure-aws-credentials@v1
```

Also, have you set up the appropriate IAM roles?

Reference: https://github.com/aws-actions/configure-aws-credentials#sample-iam-role-cloudformation-template

> Do I need to set a secrets.AWS_ACCESS_KEY_ID / secrets.AWS_SECRET_ACCESS_KEY just to assume the role? I don't understand.

You can assume role without access key and secret key because that is the advantage of using GitHub Actions OIDC.

**Comment by kaihendry** [comment]
I tried that, it doesn't work for the same reason: https://github.com/kaihendry/go-web-dynamo-starter/commits/main/.github/workflows/sam-pipeline.yml

I'm pretty sure the role is right ... 

```
(ins)[hendry@t14s ~]$ aws iam get-role --role-name github-actions-test-Role-QVSUYDA0W3QG
{
    "Role": {
        "Path": "/",
        "RoleName": "github-actions-test-Role-QVSUYDA0W3QG",
        "RoleId": "AROAV5XVAVSZKEWK2ZPX7",
        "Arn": "arn:aws:iam::407461997746:role/github-actions-test-Role-QVSUYDA0W3QG",
        "CreateDate": "2022-01-08T08:19:54+00:00",
        "AssumeRolePolicyDocument": {
            "Version": "2008-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Federated": "arn:aws:iam::407461997746:oidc-provider/token.actions.githubusercontent.com"
                    },
                    "Action": "sts:AssumeRoleWithWebIdentity",
                    "Condition": {
                        "StringLike": {
                            "token.actions.githubusercontent.com:sub": "repo:kaihendry/go-web-dynamo-starter:*"
                        }
                    }
                }
            ]
        },
        "Description": "",
        "MaxSessionDuration": 3600,
        "RoleLastUsed": {}
    }
}
```

**Comment by dyoshikawa** [comment]
@kaihendry A lack of this may be the cause.

https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931012696

**Comment by idelfonsog2** [comment]
seems to be true about defining the permissions for the configuration step. 

if you follow https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services it will help

I was having the same issue after pushing 20 commits to try different things it worked 😅

The steps:

1. Configure the Identity Provider in the IAM AWS console (use the info in the link)
2. Create a new role that includes the identity provider
3. Define the permissions in your YAML file (like below)
4. Add the **role's** ARN (not the OIDC arn) to the configuration step in the YAML

```yml
name: AWS Lambda

on:
  workflow_dispatch:
  push:
    branches: [ main ]
permissions:
      id-token: write
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:....
```

**Comment by kaihendry** [comment]
Thank you ! that fixed it, and then I'm onto https://github.com/aws-actions/configure-aws-credentials/issues/357 haha

**Comment by Smarker** [comment]
thank you so much @idelfonsog2, that fixed my issue, I was using the wrong role in my configuration step of my yaml!

**Comment by jackcohen5** [comment]
> Can you confirm that `[deploy-role]` has the exact same name as what `!Sub githuboidc__${RepoName}` in your role definition turns into?

@tedivm I am seeing a similar issue as @ohad-griiip, but I have confirmed that my role name is the same between the `role-to-assume` config and the one that's in IAM.

I'm still getting `Not authorized to perform sts:AssumeRoleWithWebIdentity` though. Any ideas what I may be missing or how I can make this error a bit more descriptive?

**Comment by notdodo** [comment]
Hi followed all the instructions provided by GitHub and in this thread by I'm still unable to load credentials.

[Action YAML](https://github.com/notdodo/tf-calibre-web/blob/main/.github/workflows/plan-on-pr.yml#L41)

```yaml
name: Plan / Test On PR

on:
  pull_request:
    branches:
      - main

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive

  plan_and_apply:
    name: Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::423779874966:role/GitHubAction # The role ARN is correct.
          aws-region: eu-west-1
      - run: aws sts get-caller-identity
   ```

Provider configuration:

![Screenshot_20220613_000652](https://user-images.githubusercontent.com/6991986/173256131-3ee99355-0864-4d8f-8bc3-3a5cd52b701f.png)

IAM Role trust configuration:

![Screenshot_20220613_000635](https://user-images.githubusercontent.com/6991986/173256134-72fed54a-a59b-41f2-b485-ec19b454a975.png)

What am I doing wrong?

**Comment by Spothedog1** [comment]
Also still failing after trying everything across multiple solutions with error
`Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers`


![actions](https://user-images.githubusercontent.com/7429961/184423364-bc67770d-8400-4538-b3f1-62577c6122a8.png)
![oidc](https://user-images.githubusercontent.com/7429961/184423367-877bc131-6e95-43e3-9104-870141aea45d.png)
![trust](https://user-images.githubusercontent.com/7429961/184423368-815f1583-865b-4bf2-9851-e570ba89ad08.png)

**Comment by cmiller-jetty** [comment]
> ```yaml
> permissions:
>   id-token: write
>   contents: read
> ```

This also fixed for me as well .

**Comment by chrisFFL** [comment]
Was getting this error until I set the environment value to match the Github environment that had all the secrets

```yml
    runs-on: ubuntu-latest
    environment:
      name: production
```

**Comment by adorDoodle** [comment]
> so i think there is an undocumented permissions thing you need to use in your workflow to get it
> 
> ```
> permissions:
>   id-token: write
>   contents: read
> ```
> 
> try that

Saved my day. Thanks man...

**Comment by jaxxstorm** [comment]
I get this error on a transient basis.

I have the correct permissions:

```
permissions:
  id-token: write
  contents: read
```

and the correct audience:

```
Run aws-actions/configure-aws-credentials@master
  with:
    role-session-name: githubactions
    aws-region: us-west-2
    audience: sts.amazonaws.com
```

This works probably 50% of the time, but sometimes it fails to retrieve credentials completely.

I'm also using the master commit

**Comment by bp-xiao** [comment]
same here.

Our workflows had worked well until yesterday, but this mourning I found th workflows began to fail without any changes.

**Comment by bp-xiao** [comment]
I digged into the problem and the problem seems to be caused by the absence of `~runner/.aws/credentials` which contains the token file path.
The line where the error is occuring is the follow:
https://github.com/aws/aws-sdk-js/blob/307e82673b48577fce4389e4ce03f95064e8fe0d/lib/credentials/token_file_web_identity_credentials.js#L159

Unfortunately, I don't know what was written in `~/.aws/credentials`, so I'm still stuck in the situation.

**Comment by bp-xiao** [comment]
In my case, I set `audience` to `sts.amazonaws.com` to solve the problem.

But I don't known why this fixes the problem, even though we han't specified `audience` until yesterday and our workflows had been working well. In addition to that the README says default `audience` is `sts.amazonaws.com` 😕 .

**Comment by peterwoodworth** [comment]
There seem to have been a number of separate issues discussed here. I'm going to close this so that people who run into this issue in the future create a new issue. Please be sure to check your permissions - they are required when using OIDC

**Comment by miparnisari** [comment]
@androidwiltron re: "so i think there is an undocumented permissions thing you need to use in your workflow to get it"

it's documented here https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#updating-your-github-actions-workflow

**Comment by Zordrak** [comment]
One thing that is not obvious that I will leave here for anyone googling to resolve their problem is that job permissions do not individually overwrite workflow permissions, the new permissions block replaces the old permissions block. They are not merged.

This means that in this configuration:

```yaml
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: build
    permissions:
      pull-requests: write
```

The `build` job will not have `id-token: write` nor `contents: read` as the effective permissions block for the job only grants `pull-requests: write`.

Personally I think that this perhaps might be a confusing design choice and that the job permissions should be deep merged into the workflow permissions, but this is how it works at the moment.

If your jobs have their own permissions applied, make sure to repeat id-token and contents.
 in your workflow permissions, but you also specify

**Comment by liam102** [comment]
I agree
> Personally I think that this perhaps might be a confusing design choice and that the job permissions should be deep merged into the workflow permissions, but this is how it works at the moment.
Merging makes more sense in terms of a reusable block.

**Comment by tmax22** [comment]
for me 
```yml
jobs:
  tests:
    uses: ./.github/workflows/run_tests.yml

```

`aws-actions/configure-aws-credentials@v4` forever fails inside the nested workflow `./.github/workflows/run_tests.yml` no matter what permissions I try to pass, is it even possible to use `aws-actions/configure-aws-credentials` action in nested workflow? I'm not sure
