### ISSUE TITLE
Error: Incorrect token audience

### ISSUE THREAD

**Issue by jatinmehrotra** [aws-actions/configure-aws-credentials#291]
Till yesterday the actions was working perfectly well, but from today I am seeing this error. Is it due to the latest commit?

```
- name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{secrets.ROLE_ARN}}
```
