### ISSUE TITLE
OIDC Provider with AWS Partitions

### ISSUE THREAD

**Issue by jwenz723** [aws-actions/configure-aws-credentials#293]
Does the ability to make use of the GitHub OIDC Provider to assume AWS roles work with AWS partitions other than the standard `aws` partition? For example, will this work with the GovCloud partition `aws-us-gov`?

I tried using the OIDC Provider with a GovCloud account and it resulted in the minimally useful error:

> The security token included in the request is invalid

Here is my workflow file:

```yaml
name: "testing oidc"

on:
  push:

jobs:
  oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials for GovCloud
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-gov-east-1
          role-to-assume: arn:aws-us-gov:iam::123456789012:role/MyRole

```

**Comment by richardhboyd** [comment]
you're setting the region to us-west-2 in those env variables

**Comment by jwenz723** [comment]
It appears that if I have this action occurring 2 times in a single workflow then the `region` set in the first step carries over into the 2nd step. Commenting out my first step causes role assumption to work in my GovCloud account. The resulting workflow is the same as above but with the first assumption step removed:

```yaml
name: "testing oidc"

on:
  push:

jobs:
  oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Test OIDC with GovCloud account
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-gov-east-1
          role-to-assume: arn:aws-us-gov:iam::<ID OMITTED>:role/temp
```

**Comment by jwenz723** [comment]
This is probably obvious, but I confirmed that if I reverse the ordering of my steps that the same failure occurs in my non-govcloud role assumption.

```yaml
name: "testing oidc"

on:
  push:

jobs:
  oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Test OIDC with GovCloud account
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-gov-east-1
          role-to-assume: arn:aws-us-gov:iam::<ID OMITTED>:role/temp

      # Test OIDC with commercial account
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::<ID OMITTED>:role/temp
```


I Also tried manually setting the env vars on the step to override what the action is exporting:

```yaml
name: "testing oidc"

on:
  push:

jobs:
  oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Test OIDC with commercial account
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::<ID OMITTED>:role/temp

      # Test OIDC with GovCloud account
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        env:
          AWS_DEFAULT_REGION: us-gov-east-1
          AWS_REGION: us-gov-east-1
        with:
          aws-region: us-gov-east-1
          role-to-assume: arn:aws-us-gov:iam::<ID OMITTED>:role/temp
```

Surprisingly this did not work. You can see that the env vars are properly set to the govcloud region, but still get the same error:
![Screen Shot 2021-10-21 at 5 11 06 PM](https://user-images.githubusercontent.com/8587171/138369135-32ccbfaa-208c-4a95-96be-77b81393e26f.png)
