### ISSUE TITLE
Create new release?

### ISSUE THREAD

**Issue by akash1810** [aws-actions/configure-aws-credentials#302]
Hi,

Really excited to see the OIDC support 🎉 . It looks like this action is also [recommended by GitHub themselves](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services), which is great because it means we can deprecate one of our [repositories](https://github.com/guardian/actions-assume-aws-role) that achieves the same thing.

It doesn't look like a release has been made since OIDC support has been added, meaning one has to use this action by reference to the default branch (`@master`):

```yaml
steps:
  - uses: actions/checkout@v2
  - uses: aws-actions/configure-aws-credentials@master # <- @v1 doesn't include OIDC changes
    with:
      role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      aws-region: eu-west-1
```

This isn't recommended. From https://github.com/actions/toolkit/blob/master/docs/action-versioning.md:

> Warning: do not reference `main` since that is the latest code and can be carrying breaking changes of the next major version.

Can a new [release](https://github.com/aws-actions/configure-aws-credentials/releases) be made?
