### ISSUE TITLE
How to configure permission for Githubaction role to initialize terraform

### ISSUE THREAD

**Issue by drey0143143** [aws-actions/configure-aws-credentials#310]
I am using Github OIDC to access my AWS which I succesfully achieved when I echo ,Hello World but I am getting an error message when it get to initialize terraform configuration.The role arn I created for GithubAction is "arn:aws:iam::123456789012:role/GitHubActions_Workflow_role"
```
terragrunt.hcl

remote_state {
  backend = "s3"
  config = {
    bucket         = "my-bucket-github-actions-workflow-terraform"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    role_arn       = "arn:aws:iam::123456789012:role/GitHubActions_Workflow_role"
    region         = "us-east-2"
    encrypt        = true
    dynamodb_table = "my-lock-table"
  }
}
provider "aws"{
  assume_role {
    role_arn = "arn:aws:iam::123456789012:role/GitHubActions_Workflow_role"
  }
}
```
```
policy attached with GithubActions_Workflow_role

data "aws_iam_policy_document" "GitHubActions" {
  statement {
    actions   = ["s3:ListAllMyBuckets"]
    resources = ["*"]
    effect    = "Allow"
  }
}
```
```
main.yml

name: 'GitHub OIDC workflow'
on:
  push:
       branches:
         - testing
env:
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: './staging/qa-env'
permissions:
    id-token: write
    contents: read
jobs:
  deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActions_Workflow_role
          role-duration-seconds: 3600

      - run: aws sts get-caller-identity
      - run: echo "Hello,World"

      - name: 'Terragrunt Init'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          TF_INPUT: false

```
```
error message:

init: info: initializing Terragrunt configuration in ./staging/qa-env
init: error: failed to initialize Terragrunt configuration in ./staging/qa-env
time=2021-11-10T20:01:26Z level=error msg=Create S3 bucket with retry my-bucket-github-actions-workflow-terraform returned an error: AccessDenied: Access Denied
	status code: 403, request id: 41T5ZW15NQFV056S, host id: 2zLqZGNyONqt4gUchyhYyBCZmQoCcohES5JQKnVrwg9zruI5eE+6cBj5t3VjhABwFu60gl49MUM=. Sleeping for 10s and will try again.
time=2021-11-10T20:02:07Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
