### ISSUE TITLE
Cannot authenticate when using trusted relationship conditions

### ISSUE THREAD

**Issue by arquadrado** [aws-actions/configure-aws-credentials#317]
Hi, I am using this action in my github workflow to authenticate via OICD but the authentication fails everytime I have conditions defined in my role's trusted relationships. I followed [this](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to set it up but something is off. I have my role and my identity provider in aws but when I have the condtions it fails. At first I had:

```
"Condition": {
  "StringEquals": {
    "token.actions.githubusercontent.com:aud": "https://github.com/octo-org",
    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
  }
}
```
 
replacing the aud url by my organization repo and the sub with my branch. After that I tried to remove the branch condition and just leave the aud one but it still fails. If I remove both conditions it logs and proceeds to be able to execute aws commands. I am assuming that the jwt is not sending the information aws exactly as I expect but I don't know how to confirm this. How can I check the token that is being sent to aws?

Here's my action conf in case that sheds some light on the problem:

```
name: "AWS deploy"
on: push
permissions:
  id-token: write
  contents: write 
jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::000000000000000:role/GithubDeploymentRole
          aws-region: us-west-2
      - name: Test aws connection
        run: |
          aws ec2 describe-vpcs
```

Any help would be very appreciated.
