### ISSUE TITLE
Override Exported Variable Names

### ISSUE THREAD

**Issue by dstarner** [aws-actions/configure-aws-credentials#322]
During our run, we need to pull in multiple AWS accounts for different resources and products. By default, this only exports to the standard `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env variables, but we would like the option to run the action multiple times and include either a `prefix` / `suffix` value for those environment variables or provide explicit override values for all of them.

```yaml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::1234:role/my-example-role

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::123456:role/my-second-role

          # The following would be the addition
          env-prefix: `SECOND`  # would result in `SECOND_AWS_ACCESS_KEY` and so on...

          # OR explicit
          access-key-env: SECOND_AWS_ACCESS_KEY
          secret-key-env: SECOND_AWS_SECRET_ACCESS_KEY
```

**Comment by kellertk** [comment]
Would you be able to accomplish this by chaining steps together and [setting environment variables](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable) yourself? Something like:

```
steps:
  - name: Get AWS credentials
    uses: aws-actions/configure-aws-credentials@v1.6.0
    with:
      aws-region: us-east-2
      role-to-assume: arn:aws:iam::1234:role/my-example-role
  - name: Rename env variables
    run: |
      echo "${{ env.AWS_ACCESS_KEY_ID }}=SECOND_AWS_ACCESS_KEY" >> $GITHUB_ENV
      echo "${{ env.AWS_SECRET_ACCESS_KEY }}=SECOND_AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
      echo "${{ env.AWS_SESSION_TOKEN }}=SECOND_AWS_SESSION_TOKEN" >> $GITHUB_ENV
  - name: Get AWS credentials
    uses: aws-actions/configure-aws-credentials@v1.6.0
    with:
      aws-region: us-east-2
      role-to-assume: arn:aws:iam::123456:role/my-second-role
````

And so on
