### ISSUE TITLE
outputs.aws-account-id is not reflecting correctly anymore

### ISSUE THREAD

**Issue by ROglesby92** [aws-actions/configure-aws-credentials#323]
Before the latest release 1.6.0, I was able to reference the output of an account id from a `configure-aws-credentials` step like so:

e.g
```yaml
     - name: Configure AWS Credentials for deployment
       id: aws-deploy-credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::123456789:role/github-actions-runner
          role-duration-seconds: 900
      
     - name: Deploy
       ...
       env:
          QUEUE_URL: https://sqs.us-west-2.amazonaws.com/${{ steps.aws-deploy-credentials.outputs.aws-account-id }}/test

```

Expected results:
QUEUE_URL should be set to `https://sqs.us-west-2.amazonaws.com/123456789/test`

Actual results:
QUEUE_URL is now set to `https://sqs.us-west-2.amazonaws.com/987654321/test`

Where `987654321` is the account ID from the Github Runners original role:
 `arn:aws:iam::987654321:role/github-actions-runner`

This caused some bad deploys to happen as my resource naming convention referenced the deploying role account id, had to end up making those values static instead
