### ISSUE TITLE
Self-Hosted Runners with NO AWS permissions will honor OIDC from a workflow?

### ISSUE THREAD

**Issue by pragmaticivan** [aws-actions/configure-aws-credentials#342]
> If you run your GitHub Actions in a self-hosted runner that already has access to AWS credentials, such as an EC2 instance, then you do not need to provide IAM user access key credentials to this action.

What happens when the self-hosted runner doesn't have access to AWS credentials?

Will the OIDC set in that block be honored `on demand` per build ?

Context: I want to have multiple pods but don't want to attribute AWS permissions for the ephemeral containers. They will have no was permissions until a new action is pulled.

```yaml
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::111111111111:role/my-github-actions-role-test
        aws-region: us-east-1
```

If so, would you mind updating the docs for Self-Hosted runners with that info?
