### ISSUE TITLE
Obtaining credentials is flaky and fails non-deterministically - possibly rate limited?

### ISSUE THREAD

**Issue by dannyfallon** [aws-actions/configure-aws-credentials#348]
I'm using this action to deploy multiple lambda functions via SAM on a GitHub Action runner. Here's a snippet of the config:

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        function: [
          func1, func2, func3, func4, func5, func6, func7
        ]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: *****
          aws-region: eu-west-1
          role-session-name: *****
      - name: eu-west-1 / ${{ matrix.function }}
        run: |
          sam build 
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: ./functions/${{ matrix.function }}
```

The use of a matrix will cause all functions (currently 7) to be deployed at the same time in parallel. I ran this action 5 times and it failed 5 times. Each time it failed it was on a different job - jobs that passed earlier failed in later runs and ones that failed earlier passed in other runs. On one occasion 5/7 jobs failed. The code is the exact same for all functions as per the config. Each time it fails a job the part that fails is `configure-aws-credentials` with this:

>Couldn't retrieve verification key from your identity provider, please reference AssumeRoleWithWebIdentity documentation for requirements

The sporadic, non-deterministic failures indicate to me that there is potentially an issue with the level of parallelism here, not my config. I'm having a hard time confirming this though. I enabled stack tracking as an env variable and get this:

```
Run aws-actions/configure-aws-credentials@master
Error: Couldn't retrieve verification key from your identity provider,  please reference AssumeRoleWithWebIdentity documentation for requirements
(node:1691) UnhandledPromiseRejectionWarning: InvalidIdentityToken: Couldn't retrieve verification key from your identity provider,  please reference AssumeRoleWithWebIdentity documentation for requirements
    at Request.extractError (/home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:2779:29)
    at Request.callListeners (/home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:34721:20)
    at Request.emit (/home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:34693:10)
    at Request.emit (/home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:9507:14)
    at Request.transition (/home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:8843:10)
    at AcceptorStateMachine.runTo (/home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:17456:12)
    at /home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:17468:10
    at Request.<anonymous> (/home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:8859:9)
    at Request.<anonymous> (/home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:9509:12)
    at Request.callListeners (/home/runner/work/_actions/aws-actions/configure-aws-credentials/master/dist/index.js:34731:18)
(node:1691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1691) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Earlier today I dropped the max parallelism to 1 on the matrix so we deploy one function at a time and I haven't encountered any issue since then. It does delay our deploys for up to 10 minutes as a result but we need reliability more than speed. That said we'd love to get both so we could get to the bottom of this that'd be great!
