### ISSUE TITLE
OIDC fails for pull request from fork

### ISSUE THREAD

**Issue by martinschaef** [aws-actions/configure-aws-credentials#373]
I have a pull request from a fork:
https://github.com/aws-samples/amazon-codeguru-samples/pull/10
both the fork and the original repo are allow-listed in my role:
```
    - name: Assume IAM Role
      continue-on-error: true
      uses: aws-actions/configure-aws-credentials@v1
      id: iam-role
      with:
        role-to-assume: arn:aws:iam::048169001733:role/GuruGitHubCICDRole
        aws-region: us-west-2

```
when I trigger only on pull_request, the action fails to get credentials:
https://github.com/aws-samples/amazon-codeguru-samples/runs/5030685457?check_suite_focus=true

However, when I trigger on push it works:
https://github.com/martinschaef/amazon-codeguru-samples/runs/5030736213?check_suite_focus=true

Any idea how to fix that? This makes it hard to use pull-request triggers with code guru
