### ISSUE TITLE
Instance profile assume Role issue

### ISSUE THREAD

**Issue by abhisharma-mcd** [aws-actions/configure-aws-credentials#378]
Hi,
I'm using this action in a workflow which is running on a self-hosted runner. Runner is configured on AWS EC2 instance which has instance profile attached. When I run the worklfow, I'm getting below issue :-

![image](https://user-images.githubusercontent.com/79092713/153197288-ba5b766e-2012-4857-a429-daeee7aff4d0.png)

As you can see, instance profile that is attached to runner server is trying to assume the role that is passed to the action instead of Access and Secret key of user.

Below is the workflow code :-
```
name: 'est worklfow'
on: 
  workflow_dispatch:
jobs: 
  test-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::111111111111:role/TEST_ROLE
          role-duration-seconds: 1200
          role-skip-session-tagging: true
      
      - name: Check S3 access
        run: aws s3 ls
```
Any idea why is it happening and how to fix it?
