### ISSUE TITLE
Unable to use in reusable workflow: `Error: The security token included in the request is invalid.`

### ISSUE THREAD

**Issue by choffa** [aws-actions/configure-aws-credentials#383]
I have been trying to use this action in a reusable workflow. Whenever I try to I get an `Error: The security token included in the request is invalid.` My motivation for using the action in this way, is to be able to do the same workflow on different accounts, depending in the circumstances, such as deploying `dev` on push, and `prod` manually.

# Reproduction steps:
My called (reusable) workflow looks as follows:
```yml
name: Deploy

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  test:
    name: Test-secrets
    runs-on: ubuntu-latest
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}
```

And the caller workflow looks like:
```yml
name: Continous Delivery

on: push

jobs:
  deploy-dev:
    name: Deploy Dev
    uses: ./.github/workflows/deploy.yml
    with:
      aws-region: eu-west-1
    secrets:
      AWS_ACCESS_KEY_ID: $${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
```

# Expected behaviour
I expect the action to work as normal, like it does when used directly, ie.
```yml
name: Continous Delivery

on: push

jobs:

  test-directly:
    name: Test Directly on push
    runs-on: ubuntu-latest
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key:  ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
```
Using the action this way works just fine. That also confirms that it is not the secrets that are the issue...

*Let me know if you need anything else!* :)
