### ISSUE TITLE
GITHUB_BASE_REF & GITHUB_EVENT_NAME Session Tag

### ISSUE THREAD

**Issue by jsimoni** [aws-actions/configure-aws-credentials#390]
We'd like to be create a trust document on the AWS Role assumed by GitHub Action workflow that only authorizes a workflow that runs on a pull request that targets a specific branch.  In order to do that, we would need this GitHub Action to populate Session Tags with the values in the GITHUB_BASE_REF & GITHUB_EVENT_NAME environmental variables.

https://github.com/aws-actions/configure-aws-credentials#session-tagging

**Comment by peterwoodworth** [comment]
We should be able to support additional, non-required environment variables as session tags. Thanks for the suggestion!

Documentation [here](https://docs.github.com/en/actions/reference/workflows-and-actions/variables#default-environment-variables) for future reference

**Comment by peterwoodworth** [comment]
You can currently work around your specific issue through your action configuration like so until we may implement this:

```
on:
  pull_request_target:
    types:
      - opened
    branches:    
      - 'master'
  push:
    branches:    
      - 'master'
```
