### ISSUE TITLE
non-EC2 self-hosted runner is not working with aws-assume-role

### ISSUE THREAD

**Issue by scott-doyland-burrows** [aws-actions/configure-aws-credentials#393]
In my action this workflow works fine on a GitHub hosted runner ```ubuntu-latest```.  However, if I alter it to run on a non-EC2 (an on-prem) Windows runner then it fails with:

```Error: Error message: Cannot read property 'message' of undefined```

I switched on GitHub Actions debugging and can see lots of errors in the logfiles which I can attach.

```
name: deploy
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: my-windows-self-hosted-runner
    steps:
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.MY_AWS_ROLE }}
...
...
```

However, this works fine, so I know my self-hosted runner actually works, so at the moment I have to continue to use AWS access keys for my on-prem runner.

```
name: deploy
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
jobs:
  test:
    runs-on: my-windows-self-hosted-runner
    steps:
...
...
```
