### ISSUE TITLE
Error object is empty breaking action

### ISSUE THREAD

**Issue by GrahamCampbell** [aws-actions/configure-aws-credentials#395]
Action stopped working today, after working for multiple weeks:

```yaml
    runs-on: ubuntu-20.04

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::[REDACTED]:role/[REDACTED]
          role-duration-seconds: 3600
          aws-region: us-east-1
```

```
Error: Error message: Cannot read property 'message' of undefined
```

**Comment by GrahamCampbell** [comment]
Seems to be kinda temperamental.

**Comment by sihil** [comment]
I've also seen this happen a couple of times today. A search (https://github.com/aws-actions/configure-aws-credentials/search?q=message) indicates that this could be an error masking another error?

**Comment by mmuth** [comment]
Same problem here... do you have any ideas where to dig into the source.. oder what to do to make it more stable or get closer to the cause of the problem?

**Comment by jverhoelen** [comment]
We're observing same flaky behaviour as of today (assuming role via OIDC). Currently we can't locate the problem and think that it's belonging to the runners - we're using default runners. One run fails, the next one again works. Very strange.

**Comment by WtfJoke** [comment]
Wild guessing here, but I noticed that while adding Github as OIDC provider in AWS, that I get different SSL Certificate thumbprints, such as:

- `6938fd4d98bab03faadb97b34396831e3780aea1` (seems like the most current one, according to [github's blog post](https://github.blog/changelog/2022-01-13-github-actions-update-on-oidc-based-deployments-to-aws/) and the example in the [configure-aws-credentials action's README](https://github.com/aws-actions/configure-aws-credentials/blob/dfe025559e832076752744d168bf2172b72c2aa7/README.md#sample-iam-role-cloudformation-template))
- `15e29108718111e59b3dad31954647e3c344a231` (aws calculated that thumbprint when I created the github oidc provider on 22.02.22)
- `a031c46782e6e6c662c2c87c76da9aa62ccabd8e` (seems to be an older one)

There is also an open issue here https://github.com/aws-actions/configure-aws-credentials/issues/357 (but the error message compared to that issue is more on point)


TLDR: You might should take a look at your thumbprint and add 693... to the list, if its not already there.

**Comment by peterwoodworth** [comment]
The issue described here must be intermittent. `message` is a property we reference on the error objects when trying various things while running this action. So these objects are sometimes empty for _some_ reason. Doesn't seem to be affecting many people consistently, if you do run into this in the future please comment on how you are trying to assume the role (e.g. OIDC or access keys)

**Comment by matthieudolci** [comment]
We are also having this flaky behaviour while assuming roles with OIDC

**Comment by pete-fl0** [comment]
Experiencing flaky behaviour assuming role via OIDC.
Using thumbprint `6938fd4d98bab03faadb97b34396831e3780aea1`

**Comment by peterwoodworth** [comment]
I'm going to also request that people share their full workflow files if possible. It seems this is limited to OIDC which is helpful to know 🙂

**Comment by egglestonbd** [comment]
We are having a similar experience, using `aws-actions/configure-aws-credentials@v1-node16`:
```
Error: Error message: Cannot read properties of undefined (reading 'message')
```
Cleaned log:
```
Run aws-actions/configure-aws-credentials@v1-node16
  with:
    role-to-assume: arn:aws:iam::***:role/some/path/some-role-1MSY53MY098H2
    aws-region: us-east-1
    role-duration-seconds: 900
    audience: sts.amazonaws.com
  env:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    ... other env vars
```

**Comment by stayman-coastpay** [comment]
We are also seeing it using oidc

**Comment by bskiff** [comment]
We're also getting intermittent failures with OIDC. It's working the majority of the time though. I don't see any logs in AWS CloudTrail for an attempted OIDC login around the time of the error.

Workflow:
```yml
- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v1.7.0
  with:
    role-to-assume: // our IAM role ARN 
    aws-region: // our AWS region
```

Output:
```
Run aws-actions/configure-aws-credentials@v1.7.0
with:
  role-to-assume: // our IAM role ARN 
  aws-region: // AWS region
  audience: sts.amazonaws.com
env:
  ...
Error: Error message: Cannot read property 'message' of undefined  
```
