### ISSUE TITLE
aws-region does not work with secrets

### ISSUE THREAD

**Issue by salatielosorno** [aws-actions/configure-aws-credentials#402]
Why can not `aws-region`  use a secret?

I tried this but it does not work:
```yaml
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: ${{ secrets.AWS_REGION }}
```

This works:
```yaml
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: us-east-1
```
