### ISSUE TITLE
Question about assuming role in self-hosted runner

### ISSUE THREAD

**Issue by kimxogus** [aws-actions/configure-aws-credentials#403]
I'm trying to assume iam roles in self-hosted runner(with IRSA in kops), and having `Not authorized to perform sts:AssumeRoleWithWebIdentity`.
I'm not sure what exactly is wrong as there's a lack of example of iam policy with self-hosted runners.
Could you review my configurations and give me some advise?

- iam role of self-hosted runner
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "OIDC_ARN"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "OIDC_URL:sub": "system:serviceaccount:namespace:name"
                }
            }
        }
    ]
}
```
- iam role to assume in github action
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "SELF_HOSTED_RUNNER_IAM_ROLE_ARN"
            },
            "Action": [
                "sts:AssumeRole",
                "sts:AssumeRoleWithWebIdentity"
            ]
        }
    ]
}
```

- workflow yaml
	- `#` comments are description of output
```yaml
name: Test

on: push

jobs:
  self-hosted:
    runs-on: [self-hosted, test]
    permissions:
      id-token: write
      contents: read

    steps:
# runner's irsa iam role is shown. session name is botocore session
    - name: awscli
      if: ${{ always() }}
      run: |
        aws sts get-caller-identity || true

# works without error
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ always() }}
      with:
        aws-region: ap-northeast-2
        role-session-name: ${{ github.workflow }}_${{ github.run_number }}_${{ github.job }}

 # role session name is not changed (botocore session is retained)
    - name: awscli
      if: ${{ always() }}
      run: |
        # runner's irsa iam role is shown
        aws sts get-caller-identity || true

# works without error
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ always() }}
      with:
        aws-region: ap-northeast-2
        web-identity-token-file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        role-session-name: ${{ github.workflow }}_${{ github.run_number }}_${{ github.job }}

# role session name is not changed (botocore session is retained)
    - name: awscli
      if: ${{ always() }}
      run: |
        # runner's irsa iam role is shown
        aws sts get-caller-identity || true

# error thrown Error: Not authorized to perform sts:AssumeRoleWithWebIdentity
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ always() }}
      with:
        aws-region: ap-northeast-2
        role-to-assume: arn:aws:iam::375255123608:role/GithubAction-test-blue
        role-session-name: ${{ github.workflow }}_${{ github.run_number }}_${{ github.job }}

# role session name is not changed (botocore session is retained)
    - name: awscli
      if: ${{ always() }}
      run: |
        aws sts get-caller-identity

# error thrown Error: Not authorized to perform sts:AssumeRoleWithWebIdentity
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ always() }}
      with:
        aws-region: ap-northeast-2
        role-to-assume: arn:aws:iam::375255123608:role/GithubAction-test-blue
        web-identity-token-file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        role-session-name: ${{ github.workflow }}_${{ github.run_number }}_${{ github.job }}

# role session name is not changed (botocore session is retained)
    - name: awscli
      if: ${{ always() }}
      run: |
        aws sts get-caller-identity
```
