### ISSUE TITLE
Not able to set externalId with GitHub action

### ISSUE THREAD

**Issue by royjit** [aws-actions/configure-aws-credentials#407]
Trying to set externalId returns the following error:

```
Unexpected key 'ExternalId' found in params
```

Created the action like this:

```
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          role-external-id: ${{ inputs.external_id }}
          aws-region: ${{ inputs.aws_region }}
          role-session-name: IntegrationRoleSessions
          role-duration-seconds: 900
```

Is there something that I am missing?
