### ISSUE TITLE
Second invocation of the action in a workflow fails.

### ISSUE THREAD

**Issue by lurbanski-equinix** [aws-actions/configure-aws-credentials#423]
```yaml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: XXXX
          aws-region: us-west-1
          aws-access-key-id: XXX
          aws-secret-access-key: XXX
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: XXXX
          aws-region: us-west-1
          aws-access-key-id: XXX
          aws-secret-access-key: XXX
          role-duration-seconds: 3600
          role-skip-session-tagging: true

```
The first is ok.
The second invocation fails with the error:
Error: The security token included in the request is invalid.
