### ISSUE TITLE
Always timeouts when trying to assume a role

### ISSUE THREAD

**Issue by dallin-defimono** [aws-actions/configure-aws-credentials#436]
### Description

When assuming a role, I always experience a timeout from AWS using this action specifically.

Works great:
```
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_GITHUB_ACTIONS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_ACTIONS_SECRET_ACCESS_KEY }}
#          role-to-assume: arn:aws:iam::${{ secrets.AWS_SHARED_SERVICES_ACCOUNT_ID }}:role/system/github-actions-external-access
```

I can verify that assuming the role works 100% when ran from a local CLI like so, verifying the sts assume role, tagging permissions, etc. are all functioning correctly.

`aws sts assume-role --role-arn arn:aws:iam::<account_id>:role/system/github-actions-external-access --role-session-name dev --region eu-west-1`

and I am able to get credentials, and do what I need to do.

I can also confirm it is something internal in the action. When I call the assume role logic from bash on the github runner like so, it works 100%.

```
Run eval $(aws sts assume-role --role-arn arn:aws:iam::***:role/system/github-actions-external-access --role-session-name test | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)\nexport AWS_SESSION_TOKEN=\(.SessionToken)\n"')
"arn:aws:sts::***:assumed-role/github-actions-external-access/test"
```

However as soon as I uncomment the role to assume line and run it in Github actions, the exact same role as called via the CLI, and I now experience failures that manifest via timeouts with error:

### Error
`Error: The requested DurationSeconds exceeds the MaxSessionDuration set for this role.`

### Workflow File
This is the entirety of the failing workflow file as well.

```
name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Scan and Deploy Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_GITHUB_ACTIONS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_ACTIONS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_SHARED_SERVICES_ACCOUNT_ID }}:role/system/github-actions-external-access
          role-session-name: github
```

### Temporary workaround 

Currently I am using this hacky workaround, as this will set the environment to what I need but this is much worse then the action itself, but it works at least. This however does have a small side effect of leaking the temp credentials.

```
      - name: raw assume
        run: |
          eval $(aws sts assume-role --role-arn arn:aws:iam::${{ secrets.AWS_SHARED_SERVICES_ACCOUNT_ID }}:role/system/github-actions-external-access --role-session-name test | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)\nexport AWS_SESSION_TOKEN=\(.SessionToken)\n"')
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_ENV

      - name: Test creds
        run: |
          aws sts get-caller-identity --query Arn
```
