### ISSUE TITLE
Action fails if `environment` is set

### ISSUE THREAD

**Issue by jkondratowicz** [aws-actions/configure-aws-credentials#452]
Hi,

When `environment` is set on a GHA that uses `aws-actions/configure-aws-credentials` action, it fails with the following error:
`Error: Not authorized to perform sts:AssumeRoleWithWebIdentity`

The exact same job without an environment set works correctly. My best guess is that adding `environment` seems to somehow change the `sub` on the token?

Steps to reproduce:
1. Create identity provider in AWS and a role, in my case trust policy of the role looks like this:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::000000000000:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "ForAllValues:StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "ForAllValues:StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:myorganization/*:ref:refs/heads/*"
                }
            }
        }
    ]
}
```
2. Paste role's ARN as `AWS_OIDC_IAM_ROLE_ARN` secret in the repository
3. Push to `main` branch of the repository

This is the workflow:
```yml
name: Test OIDC

on:
  push:
    branches:
      - main

jobs:
  withoutenv:
    name: Without environment set
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Credentials 1
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2 # v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_ARN }}
          aws-region: eu-west-2
  withenv:
    name: With environment set
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
    steps:
      - name: Credentials 2
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2 # v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_ARN }}
          aws-region: eu-west-2
```

Note that jobs only differ in that the second one specifies the environment (`dev`). The first job is successful, second one fails after retrying for ~2 minutes with error: "Error: Not authorized to perform sts:AssumeRoleWithWebIdentity".

![image](https://user-images.githubusercontent.com/3799879/172365953-c09e172c-f2b1-415a-b8a0-2ca53c9836fc.png)

Not sure if there's a way in AWS to debug what is the exact `sub` it sends on the second try?
