### ISSUE TITLE
Incorrect token audience with AWS China region

### ISSUE THREAD

**Issue by nooperpudd** [aws-actions/configure-aws-credentials#457]
action with the iam role 
```yaml
uses: aws-actions/configure-aws-credentials@v1
    with:
        role-to-assume: arn:aws-cn:iam::xxxxxx:role/terragrunt
        role-session-name: github-action
        aws-region: cn-north-1
```
<img width="1410" alt="截屏2022-06-17 15 44 50" src="https://user-images.githubusercontent.com/1549732/174251721-91939e92-0e5b-485f-a6a6-05588faa2477.png">

iam role policy
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws-cn:iam::xxxxxxxx:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:sub": "repo:xxxxxx/xxxxxxxxxxxxx:ref:refs/heads/main"
                }
            }
        }
    ]
}
```

error message:  `Error: Incorrect token audience`

[Beijing Region Endpoints](https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Beijing.html)
[Ningxia Region Endpoints](https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Ningxia.html)

Beijing STS: sts.cn-north-1.amazonaws.com.cn, 
Ningxia STS: sts.cn-northwest-1.amazonaws.com.cn

```
##[debug]ID token url is https://pipelines.actions.githubusercontent.com/NzAIyiuy4tuga9LIOHtYkwjblAphplgC9tW9NM0QoU7LqwWHx7/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/d6515396-4c89-4c0f-a5cf-8c5a42b61a2d/jobs/7f892af8-267f-55bf-a254-32b5ccdbaa41/idtoken?api-version=2.0&audience=sts.amazonaws.com
check_suite_focus=true#step:3:177)

```
