### ISSUE TITLE
Assume role throws an unauthorized error and it shouldn't

### ISSUE THREAD

**Issue by HanwhaARudolph** [aws-actions/configure-aws-credentials#465]
# Issue
When I add the `role-to-assume` arg in my step for `aws-actions/configure-aws-credentials@v1`, I get the following error:
```
Error: User: arn:aws:iam::***:user/[IAMUSERNAME] is not authorized to perform: sts:TagSession on resource: ***
```
but I have not passed it a session name to use, which based on the CLI output is required. I tried adding in the session name and got the same error.

# Reproduction steps
Use the following commands in a github pipeline to reproduce issue:
```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.APPID }}
          aws-secret-access-key: ${{ secrets.APPSECRET }}
          aws-region: ${{ secrets.REGION }}
          role-session-name: GitHubPipeline
          role-to-assume: ${{ secrets.DEV_ROLE }} 
```
To prove that its not a permission issue:
```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.APPID }}
          aws-secret-access-key: ${{ secrets.APPSECRET }}
          aws-region: ${{ secrets.REGION }}
        
      - name: Debug
        run: |
          aws sts assume-role --role-arn ${{ secrets.DEV_ROLE }} --role-session-name GitHubPipeline
```
