### ISSUE TITLE
Auth expiring sooner than expected during my github action

### ISSUE THREAD

**Issue by jiwidi** [aws-actions/configure-aws-credentials#488]
Hi

I have a github action that assumes a role with the aws auth action and starts a codebuild project. It keeps checking on its state and finishes whenever the project does. My problem is that if the project takes longer than 1h then the authentification inside the github runner expires and outputs:

```
An error occurred (ExpiredTokenException) when calling the BatchGetBuilds operation: The security token included in the request is expired
```

My github action looks like this:
```
# Runs codebuild pipeline test
name: Codebuild script

permissions:
  id-token: write
  contents: read

on:
 push

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
     - name: Clone repo
       uses: actions/checkout@v3

     - name: configureawscredentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         role-to-assume: arn:aws:iam::XXXXXXXXXXXX:role/ROLENAME
         role-session-name: SESSION_NAME
         aws-region: REGION
         role-duration-seconds: 7200

     - name: Codebuild unit test
       run: start_codebuild.sh
```

On my IAM console I have setup the role ROLENAME the maximum session to 8h instead of the default 1h (that was my first thought of why this happened) as well as passing the `role-duration-seconds` parameter to 2h in the github action call.

Any idea why this is happening? Is there any other settings I should change to the role ROLENAME?
