### ISSUE TITLE
Error: Missing a required claim: sub

### ISSUE THREAD

**Issue by pporee** [aws-actions/configure-aws-credentials#502]
Hello, i got this error when using your action : `Error: Missing a required claim: sub`

Here is my workflow:
```
jobs:
  build:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: JWT Token
        run: |
          echo "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" > /tmp/github-identity-token

      - name: Configure AWS credentials from Dev account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::xxxxxxxxxxx:role/role
          aws-region: us-east-1
          role-session-name: xxxxx
          web-identity-token-file: /tmp/github-identity-token
```
Runners are running in AWS EKS cluster, role is well created and provider.
If someone got an hint :)
