### ISSUE TITLE
Not authorized to perform sts:AssumeRoleWithWebIdentity with specific branch name 

### ISSUE THREAD

**Issue by Office-Manager** [aws-actions/configure-aws-credentials#511]
### Describe the bug

Hi all , 

I've been using the OIDC successfully but have started to tighten the permissions however I'm running into the issue 
```
Error: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

My trust policy looks like 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "RoleForGitHubActions",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::XXXXXXXXXX:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:MYORG/operations:ref:refs/heads/main",
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

Within github actions I have a prestep as well 
```
Run echo ${GITHUB_REF}
refs/heads/main
```

so I believe I have the correct setup. 

If i change the trust policy to `repo:MYORG/operations:*`  it will work but that puts me back to square one. 

### Expected Behavior

`Run aws-actions/configure-aws-credentials@v1`  completes successfully on the main branch

### Current Behavior

```
Run aws-actions/configure-aws-credentials@v1
Error: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

It fails to work when a specific branch is mentioned in  `token.actions.githubusercontent.com:sub": "repo:MYORG/operations:ref:refs/heads/main"` 

### Reproduction Steps

```
on:
  push:
    branches:
      - main
```
```

    permissions:
      id-token: write 
```

```
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ matrix.env.account }}:role/oidc-role
          aws-region: eu-west-1
          role-duration-seconds: 3600
          role-session-name: ${{ matrix.env.name }}

```

**Comment by peterwoodworth** [comment]
Sorry to hear you're running into this issue @Office-Manager,

I'm not able to reproduce this, here's my trust policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::123456789012:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:peterwoodworth/test:ref:refs/heads/main"
                },
                "ForAllValues:StringEquals": {
                    "token.actions.githubusercontent.com:iss": "https://token.actions.githubusercontent.com",
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

And here's my workflow file:

```
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: self-hosted
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::123456789012:role/GithubOIDCRole
        role-duration-seconds: 28800
        aws-region: us-east-1
```

The only difference I see that might be making a difference is that you don't have `contents` defined in your permissions. This could potentially be necessary to detect the branch, however I'm unsure and that might be wrong. Let me now if that helps or if you have any other information which may help us here 🙂
