### ISSUE TITLE
Suggested approach for multi-account deployments

### ISSUE THREAD

**Issue by AutomationD** [aws-actions/configure-aws-credentials#55]
Hello, 

What would be the suggested approach for multi-account deployments?
Let's say I have "stage" and "live" accounts. Should I have one workflow that covers deployment to all environments in stage and live, or should I have separate workflows, one for stage one for live?

Also, in the scenario of workflow-per-account I would have fairly large duplicate yaml codebase, and in the case of one workflow, there is an issue with passing STAGE and LIVE creds.

Please advise. thank you

**Comment by clareliguori** [comment]
I would suggest checking out the GitHub Actions forum for advice on how to best organize your workflows: https://github.community/t5/GitHub-Actions/bd-p/actions

As far as using this action with multiple accounts, the action can be repeated if you need multiple sets of credentials in a single workflow:
```
    - name: Configure AWS credentials for Staging
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy files to Staging bucket
      run: |
        aws s3 sync . s3://my-staging-bucket

    - name: Configure AWS credentials for Prod
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy files to Prod bucket
      run: |
        aws s3 sync . s3://my-prod-bucket

```
