### ISSUE TITLE
Error: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint

### ISSUE THREAD

**Issue by andrewdavey** [aws-actions/configure-aws-credentials#579]
### Describe the bug

My github workflows that use `aws-actions/configure-aws-credentials@v1-node16` have stopped working today. No changes have been made recently to the workflows, or my AWS accounts.

### Expected Behavior

The step should succeed without any error.

### Current Behavior

Error logged in the GitHub runner

```
Run aws-actions/configure-aws-credentials@v1-node16
  with:
    role-to-assume: arn:aws:iam::xxxxxxxxxxx:role/github-actions-role
    aws-region: eu-west-2
    audience: sts.amazonaws.com
Error: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint
```

### Reproduction Steps

I've copied what I think are the relevant parts of my workflow yml.

```
name: Test Workflow
on: push
permissions:
  id-token: write
  contents: read
env:
  aws_tools_account: "00000000000"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials: Tools account"
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ env.aws_tools_account }}:role/github-actions-role
          aws-region: eu-west-2
```
