### ISSUE TITLE
Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

### ISSUE THREAD

**Issue by arokem** [aws-actions/configure-aws-credentials#58]
Thanks for making this available! 

Following the instructions in the README, I have added this block in [my action config](https://github.com/nrdg/cloudknot/blob/69589d38d16d0e5baaf5dae9d640737cb27df190/.github/workflows/test.yml)

```
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
```

And I am getting the error in the title of the issue (see [here](https://github.com/nrdg/cloudknot/runs/651759721)).  Am I missing something? 

Thanks again!
