### ISSUE TITLE
Missing Authentication Token

### ISSUE THREAD

**Issue by kim00425** [aws-actions/configure-aws-credentials#585]
### Describe the bug

Today I did a lambda deployment with my code. But I got the message 'Missing Authentication Token'.

When I deployed to my local environment, it was deployed normally. But when I try to deploy from git-actions. It failed with the message 'Missing Authentication Token'.

What should I check??  this is my action.yml
```
permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      STAGE: prod

    steps:
      - name: Checkout sources
        with:
          ref: ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Configure AWS credentials for Production
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Downgrade NPM to v8
        run: |
          npm install -g npm@8 npm-cli-login
      - name: Install Serverless Framework
        run: npm install -g serverless@1
      - name: Install Node Modules
        run: npm ci
      - name: Serverless deploy
        run: sls deploy --conceal --stage ${{ env.STAGE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
```

![스크린샷 2022-11-28 오후 4 49 54](https://user-images.githubusercontent.com/23546154/204252587-d6a19fd1-4da4-47d6-8ec8-99832fb7eedf.png)

### Expected Behavior

i wanna successful deploy

### Current Behavior

![스크린샷 2022-11-28 오후 4 49 54](https://user-images.githubusercontent.com/23546154/204252587-d6a19fd1-4da4-47d6-8ec8-99832fb7eedf.png)

### Reproduction Steps

i dont have
