### ISSUE TITLE
Provide a way to allow multiple accounts?

### ISSUE THREAD

**Issue by wyllie** [aws-actions/configure-aws-credentials#59]
I'm wonder if there might be a way to allow access to multiple AWS accounts.  I've built an action that packages my code with all of my dependencies and installs the package as a lambda layer.  What I'd like to be able to do is have the layer installed in the sandbox account (I'm using Organizations) so that the branch gets installed into their account. 

So something like (not exactly sure what the YAML syntax would be):
```
       - name: Configure AWS credentials                                         
          uses: aws-actions/configure-aws-credentials@v1                          
          with:                                                                   
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_github.actor}}                                            
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_github.actor }}           
            aws-region: us-east-2    
```
and then specify all of the accounts in github secrets with user names appended - for example  `AWS_ACCESS_KEY_ID_wyllie`.  The idea would be that a developer would get a new version of the layer to test with their lambda functions whenever they push their code.

I guess a work around would be to have all the layers in one account and have them accessible to the sandbox accounts - I'm not sure if that would be an easy thing to configure though

**Comment by clareliguori** [comment]
@wyllie To confirm, you are trying to create a GitHub Actions workflow file where the names of the secrets used are dynamic based on the username of the developer that pushed the commit?

GitHub Actions has a `format` function that can help you do that:
https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

```
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', github.actor)] }}
        aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', github.actor)] }}
        aws-region: us-east-2
```
