### ISSUE TITLE
Cannot use EC2 authentication on self-hosted runner when workflow has "id-token: write"

### ISSUE THREAD

**Issue by fh-yuxiao-zeng** [aws-actions/configure-aws-credentials#598]
### Describe the bug

I'm using a self-hosted runner on EC2. The EC2 has a corresponding instance profile which allows it to assume a different role (a deploy role). In the workflow, the configure-aws-credentials action is used to assume that role.

Previously this action worked well. However, after I enabled Github OIDC by adding `id-token: write` permission to the workflow (for a different service), the action starts to use OIDC and throw an error `No OpenIDConnect provider found in your account for https://token.actions.githubusercontent.com/`.

### Expected Behavior

The action should still use EC2 authentication.

### Current Behavior

The actoin will prefer Github OIDC and thus throw an error.

### Reproduction Steps

This is how I'm using the action:

```yaml
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::<account>:role/<role>
        role-duration-seconds: 3600
```

### Possible Solution

Can we add an option to disable OIDC?

### Additional Information/Context

I'm completely blocked -- I'm not able to find a way to work around this behavior. If there's a temporary workaround I'm also happy to try!

**Comment by peterwoodworth** [comment]
We check for OIDC here https://github.com/aws-actions/configure-aws-credentials/blob/4b942d82b09352f2fe0ab51f6aaf75fef217ed6a/index.js#L313-L318

Is `ACTIONS_ID_TOKEN_REQUEST_TOKEN` populated in your runner?

**Comment by fh-yuxiao-zeng** [comment]
Hi @peterwoodworth, yes it is populated. It's populated once I add `id-token: write` permission to the workflow.

**Comment by peterwoodworth** [comment]
Yeah, this makes sense. We should add a way to manually override this assumption for a use case like this. Thanks for reporting, and sorry for the blocker!

**Comment by mucahitkantepe** [comment]
We are hitting the same issue but for some reason, we only hit it when we use reusable workflows not otherwise 🤔

**Comment by johnhoran** [comment]
Temporary workaround is to get the instance credentials for EC2 yourself and then pass them to configure-aws-credentials.
``` yaml
    - name: Get instance credentials
      uses: actions/github-script@v6
      id: instance_creds
      with:
        script: |
          const http = require('http');
          const role = await new Promise((resolve, reject) => {
            http.get('http://169.254.169.254/latest/meta-data/iam/security-credentials', (res) => {
              let data = '';
              res.on('data', chunk => data += chunk);
              res.on('error', err => reject(err));
              res.on('end', () => resolve(data));
            });
          });
          const credentials = await new Promise((resolve, reject) => {
            http.get('http://169.254.169.254/latest/meta-data/iam/security-credentials/' + role, (res) => {
              let data = '';
              res.on('data', chunk => data += chunk);
              res.on('error', err => reject(err));
              res.on('end', () => resolve(JSON.parse(data)));
            });
          });

          core.setSecret(credentials.AccessKeyId);
          core.setSecret(credentials.SecretAccessKey);
          core.setSecret(credentials.Token);
          core.setOutput('access_key_id', credentials.AccessKeyId);
          core.setOutput('secret_access_key', credentials.SecretAccessKey);
          core.setOutput('session_token', credentials.Token);
              
   - name: Assume AWS ECR role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ....
        aws-region: ....
        aws-access-key-id: ${{ steps.instance_creds.outputs.access_key_id }}
        aws-secret-access-key: ${{ steps.instance_creds.outputs.secret_access_key }}
        aws-session-token: ${{ steps.instance_creds.outputs.session_token }}
```

**Comment by peterwoodworth** [comment]
@fh-yuxiao-zeng I'm not sure what exactly our action is doing with how you've configured it:

```
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::<account>:role/<role>
        role-duration-seconds: 3600
```

If this worked before enabling `id-token: write`, how did that work? When setting these variables like this, it should only ever attempt to assume the role with OIDC

**Comment by fh-yuxiao-zeng** [comment]
We were trying to use OIDC for another service -- Hashicorp Vault.

Previously, the workflow only interacted with AWS API. For AWS authentication, we were using the EC2 instance role of the self-hosted runner. The workflow file looks like this:

```yaml
# OIDC not enabled

jobs:
  deploy-job:
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::<account>:role/<role>
        role-duration-seconds: 3600
```

Later, we needed to add an integration with Vault. The plan was to use Github OIDC to authenticate with Vault, so the workflow file looks like this:

```yaml
permissions:
  id-token: write

jobs:
  deploy-job:
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::<account>:role/<role>
        role-duration-seconds: 3600

    - name: Log into Vault
      uses: hashicorp/vault-action@v2
      with:
        url: https://vault-cluster.private.vault.xxx.aws.hashicorp.cloud:8200/
        method: jwt
        path: xxx
        role: xxx
```

However, this breaks the AWS part. Now `aws-actions/configure-aws-credentials` uses Github OIDC instead of EC2 instance role, so it doens't work for us.
