### ISSUE TITLE
Can't input "http-proxy" when using v1

### ISSUE THREAD

**Issue by a-kobori** [aws-actions/configure-aws-credentials#637]
### Describe the issue

Below is the log of my GitHub Actions.

```
Warning: Unexpected input(s) 'http-proxy', valid inputs are ['audience', 'aws-access-key-id', 'aws-secret-access-key', 'aws-session-token', 'aws-region', 'mask-aws-account-id', 'role-to-assume', 'web-identity-token-file', 'role-duration-seconds', 'role-session-name', 'role-external-id', 'role-skip-session-tagging']
Run aws-actions/configure-aws-credentials@v1-node16
  with:
    aws-region: ap-northeast-1
    role-to-assume: ******
    role-session-name: ******
    http-proxy: http://******:3128/
    audience: sts.amazonaws.com
```

`action.yml` of v1(also v1-node16, v1.7.0) doesn't have 'http-proxy' input.
So, I can't input it.

`README.md` let us use v1 too.

```
uses: aws-actions/configure-aws-credentials@v1
with:
  aws-region: us-east-2
  role-to-assume: my-github-actions-role
  http-proxy: "http://companydomain.com:3128"
```

FYI, 'http-proxy' is added by the below commit.
https://github.com/aws-actions/configure-aws-credentials/commit/c719b7b5e1d04c14edc4ed28f4ac39d5385d9d28

## Resolve idea

- Release new (minor) version.
- Modify README.md to let use latest commit(master branch)
