### ISSUE TITLE
Using `aws-actions/configure-aws-credentials@v1-node16` is broken (bundle is missed dep `aws-sdk`)

### ISSUE THREAD

**Issue by dhermes** [aws-actions/configure-aws-credentials#670]
### Describe the bug

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'aws-sdk'
Require stack:
- /home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.159 (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:2694:33)
    at __nccwpck_require__ (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:2809:43)
    at /home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:2830:13
    at /home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:3210:3
    at Object.<anonymous> (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:3213:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js'
  ]
}
```

### Expected Behavior

Continue working as-is

### Current Behavior

The action is not working

### Reproduction Steps

Use the branch at a19d8471766ca743361afb0250984ad3b9f923c9.

### Possible Solution

Revert the branch back to 567d4149d67f15f52b09796bea6573fc32952783.

It appears you haven't used `ncc` to rebuild or used it but didn't install packages first?

**Comment by jessebye** [comment]
FYI @kellertk . I will close duplicate issue #671 which I reported at almost the same time as this one :sweat_smile:

**Comment by dhermes** [comment]
For any readers, you can workaround this in the meantime by changing

```yaml
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
        role-session-name: MySessionName
        mask-aws-account-id: false
```

to

```yaml
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@567d4149d67f15f52b09796bea6573fc32952783
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
        role-session-name: MySessionName
        mask-aws-account-id: false
```
