### ISSUE TITLE
Error: Cannot find module 'aws-sdk' on v1-node16 branch

### ISSUE THREAD

**Issue by jessebye** [aws-actions/configure-aws-credentials#671]
### Describe the bug

We receive an error "Cannot find module 'aws-sdk'" when using `configure-aws-credentials` on the `v1-node16` branch. This just began happening, apparently after [this commit](https://github.com/aws-actions/configure-aws-credentials/commit/a19d8471766ca743361afb0250984ad3b9f923c9) was pushed.

### Expected Behavior

No error while configuring credentials.

### Current Behavior

We receive this error:

```
 node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'aws-sdk'
Require stack:
- /home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.159 (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:2694:33)
    at __nccwpck_require__ (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:2809:43)
    at /home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:2830:13
    at /home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:3210:3
    at Object.<anonymous> (/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js:3213:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/aws-actions/configure-aws-credentials/v1-node16/dist/index.js'
``` 

### Reproduction Steps

Use this action in a pipeline, pinned to the v1-node16 branch:

```yaml
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
        role-session-name: MySessionName
        mask-aws-account-id: false
```

### Possible Solution

It appears that the error was introduced by [this commit](https://github.com/aws-actions/configure-aws-credentials/commit/a19d8471766ca743361afb0250984ad3b9f923c9). So reverting that commit could fix things until the root issue is discovered.

### Additional Information/Context

@kellertk tagging you here since you pushed the possibly problematic commit.
