### ISSUE TITLE
Github Environments not working with AWS

### ISSUE THREAD

**Issue by nickls** [aws-actions/configure-aws-credentials#672]
### Describe the bug

When using Github environments with `configure-aws-credentials` it fails when the AWS trust policy restricts to the environment.

When the trust policy has a wildcard it works normally.

### Expected Behavior

No error and the GitHub action step `configure-aws-credentials` returns valid credentials for the role. :)

### Current Behavior

Error:
```
Not authorized to perform sts:AssumeRoleWithWebIdentity
```

### Reproduction Steps

Enviroment:`dev`
Repo: `sample-org/sample-repo`

AWS Trust Policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::########:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:sub": "repo:sample-org/sample-repo:environment:dev",
                    "token.actions.githubusercontent.com:iss": "https://token.actions.githubusercontent.com",
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

github-action-file.yaml
```
name: infra deploy
on:
  push:
    branches:
      - deploy-dev

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_FOR_GITHUB }}
          role-session-name: GitHubActions
          aws-region: us-east-1
```

### Additional Information/Context

The ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variable has a token that looks like this:

```
{
  "nameid": "dddddddd-dddd-dddd-dddd-dddddddddddd",
  "scp": "Actions.GenericRead:00000000-0000-0000-0000-000000000000 Actions.Results:28c652a3-303d-4186-9a3b-1a1d56297856:e07742bd-189a-5079-918b-43f8b2f94b89 Actions.UploadArtifacts:00000000-0000-0000-0000-000000000000/1:Build/Build/20 DistributedTask.GenerateIdToken:28c652a3-303d-4186-9a3b-1a1d56297856:e07742bd-189a-5079-918b-43f8b2f94b89 LocationService.Connect ReadAndUpdateBuildByUri:00000000-0000-0000-0000-000000000000/1:Build/Build/20",
  "IdentityTypeClaim": "System:ServiceIdentity",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/sid": "DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD",
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/primarysid": "dddddddd-dddd-dddd-dddd-dddddddddddd",
  "aui": "97958242-bfdf-42e4-a8a5-c0e0e3a3a7eb",
  "sid": "4b3eb703-c121-42ae-92e1-bd2d3fd4dd53",
  "ac": "[{\"Scope\":\"refs/heads/deploy-dev\",\"Permission\":3},{\"Scope\":\"refs/heads/main\",\"Permission\":1}]",
  "acsl": "10",
  "oidc_extra": "{\"ref\":\"refs/heads/deploy-dev\",\"sha\":\"deb305d264522c3c4a336d9934b918654c141fdd\",\"repository\":\"sample-org/sample-repo\",\"repository_owner\":\"sample-org\",\"repository_owner_id\":\"#######\",\"run_id\":\"42799671\",\"run_number\":\"19\",\"run_attempt\":\"1\",\"repository_visibility\":\"private\",\"repository_id\":\"453675334\",\"actor_id\":\"36834234\",\"actor\":\"nickls\",\"workflow\":\"infra deploy\",\"head_ref\":\"\",\"base_ref\":\"\",\"event_name\":\"push\",\"ref_type\":\"branch\",\"workflow_ref\":\"sample-org/sample-repo/.github/workflows/sam-pipeline.yaml@refs/heads/deploy-dev\",\"workflow_sha\":\"deb305d264522c3c4a336d9934b918654c141fdd\",\"environment\":\"dev\",\"environment_node_id\":\"EN_XXXXXXXXXX\",\"job_workflow_ref\":\"sample-org/sample-repo/.github/workflows/sam-pipeline.yaml@refs/heads/deploy-dev\",\"job_workflow_sha\":\"deb305d264522c3c4a336d9934b918654c141fdd\",\"runner_environment\":\"github-hosted\"}",
  "oidc_sub": "repo:sample-org/sample-repo:environment:dev",
  "orchid": "28c321a3-212d-4956-9a3b-1a1d56283856.deploy.__default",
  "iss": "vstoken.actions.githubusercontent.com",
  "aud": "vstoken.actions.githubusercontent.com|vso:fd985bde-aa48-4a77-8312-ae17e370b36c",
  "nbf": 1677460314,
  "exp": 1677483114
}
```

The `oidc_sub` which I assume becomes `sub` exactly matches the trust policy.

When the trust policy is more open it works:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::########:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:sample-org/sample-repo:*"
                },
                "ForAllValues:StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
                    "token.actions.githubusercontent.com:iss": "https://token.actions.githubusercontent.com"
                }
            }
        }
    ]
}
```

**Comment by kevinhaas** [comment]
Also seeing this. I see some past issues like #452 and it seems to have worked, but I couldn't get it using the environment style string from the docs.

**Comment by heggenu** [comment]
I tested this in GH Enterprice with the policy defined by the official GitHub Documentation: https://docs.github.com/en/enterprise-server@3.8/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

AWS Cloudtrail reports the subject as being:  "subjectFromWebIdentityToken": "repo:sample-org/sample-repo:ref:refs/heads/sample-branch" and not "repo:sample-org/sample-repo:environment:dev"

`"Condition": {
  "StringEquals": {
    "HOSTNAME/_services/token:aud": "sts.amazonaws.com",
    "HOSTNAME/_services/token:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
  }
}`

You can find similar condition for the public GitHub.com documentation: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

`"Condition": {
  "StringEquals": {
    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
  }
}`

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this - using an environment and specifying for it in the trust policy according to GitHub documentation works for me. Here's my setup:

```json
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::123456789012:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:myorg/myrepo:environment:myenv"
                }
            }
        }
    ]
}
```

With this being my workflow:

```yaml
jobs:
  oidc:
    runs-on: ubuntu-latest
    environment: myenv
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Assume OIDC Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::123456789012:role/myoidcrolename
    - name: List Buckets
      run: |
        aws s3 ls
```

I'd really like to help more aside from sharing my configuration, but unfortunately @nickls it looks to me like you've configured this properly. The difference in how we're checking for what exactly the value is in the trust policy isn't affecting anything as far as I can tell (plus I tested it how you set it up with `ForAllValues:StringEquals`).

@heggenu the `sub` claim _should_ include the environment if the environment is used in the job. This is described in the [enterprise docs](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#filtering-for-a-specific-environment)

**Comment by davidweterings** [comment]
I'm having this problem too. The only difference I can see is that we're using a reusable workflow in a different private repository (https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-with-your-organization). Essentially our reusable workflow looks like this:

```
on:
  workflow_call:
    inputs:
      environment:
        description: "GitHub enterprise deployment environment name"
        required: true
        type: string
      aws_role:
        description: "AWS role to assume"
        required: true
        type: string      
      aws_region:
        description: "AWS region to login to"
        required: true
        type: string

        
jobs:
  some-step:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef #v2.0.0
        with:
          role-to-assume: ${{ inputs.aws_role }}
          aws-region: ${{ inputs.aws_region }}
          role-session-name: some-session-name
```

This was to share GitHub environment secrets with the reusable workflow.
