### ISSUE TITLE
GitHub OIDC with AWS (Error: The security token included in the request is invalid.)

### ISSUE THREAD

**Issue by ashishjullia96** [aws-actions/configure-aws-credentials#681]
### Describe the bug

Hi, 

I'm in a weird situation right now (as per my understanding of the scenario).

I've setup the github oidc on aws as idp for my organization and later I started using the following:

```yaml
     - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ vars.ROLE }}
          role-session-name: "${{ github.run_id }}-${{ github.sha }}"
          aws-region: ${{ vars.AWS_REGION }}
```

I created a role^ on aws's side and added a trust relationship for that role to:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<accoiunt-id>:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:<org-name>/<repo-1>:*"
                }
            }
        }
    ]
}
```

Now, on this repo github's oidc setup is working fine, as in -> I do not have to separately create an IAM user for the repo itself, temp credentials are given by this oidc trust setup.

My question is:
Does this setup auto enforces all the repos under an account or org to only use oidc temp creds approach or let's say I've another repo as in `repo-2` -> can I use simple IAM user level approach even when the oidc setup is configured.

Note: I've only created the oidc setup to used by specific repos and want other repos to use dedicated iam users

Is it possible? or I'm missing somethig -> The official docs does not show anything related to this.

### Expected Behavior

Even after setting up the github oidc with aws, it should allow to use dedicated iam user credentials for separated repositories.

### Current Behavior

Also, on the `repo-2`, I'm getting the following error when using:
```yaml
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
```

Error:
`Error: The security token included in the request is invalid.`
![image](https://user-images.githubusercontent.com/125162454/222868641-8af8344a-6fb2-469e-9f3f-917245ded6dd.png)

### Reproduction Steps

Setup github OIDC and with aws at org level and use two separate repos:

1. Use gh oidc `role-to-assume` approach - will work as providing short term auto creds for 1 hour, only to this repo (say repo-1)
2. Use dedicated iam user's cred - will work as directly providing key and id or iam user, only for this repo (say repo-2)

**Comment by peterwoodworth** [comment]
I'm having a bit of trouble understanding the bug report here. But, there's nothing that should be preventing you from using OIDC / IAM users / whatever other method you'd like to use. [The way credentials are passed into the action](https://github.com/aws-actions/configure-aws-credentials#assuming-a-role) when you call it is what determines the method the action uses to fetch and set credentials. The fact that you've configured OIDC to work in a repo won't prevent other methods from being able to be used.

If you're still running into issues, could you please more clearly describe the situation? It's unclear to me what exactly you're trying to do in `repo-1` vs `repo-2`, could you please share the full workflow files you're using and complete reproduction steps?

**Comment by ashishjullia** [comment]
@peterwoodworth 
Almost all the other repositories are using the same approach on a particular repo is throwing this error.
I don't have more information to share :/ 

Also, I confirmed that "yes" mixture of authentication methods do works irrespective of account and repo, so "ok" on that and thanks.

To describe more, I've the following actions configured:
```
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
```
And secrets as:
![image](https://user-images.githubusercontent.com/11252951/224430099-b9e6fe70-aa0a-41d0-b4d6-0bacb2af61fa.png)

This `yaml` was working completely fine 3 months ago, no changes are made and now all of a sudden, it is throwing the following error:
![image](https://user-images.githubusercontent.com/11252951/224430279-a751582d-18f6-4342-908c-46b095d6eafc.png)

Does it has anything to do with the I am user's permission level? Or something else on gh's side (which got changed in pas 3 months).
