### ISSUE TITLE
Organization secrets don't work

### ISSUE THREAD

**Issue by GaboFDC** [aws-actions/configure-aws-credentials#69]
Github recently released the feature to setup secrets at organization level.
I tried setting up `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` there and tried to use them with the action like:

```
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
```

But the actions fails:

```
Run aws-actions/configure-aws-credentials@v1
  with:
    aws-region: us-east-1
  env:
    PATH: /home/runner/.rubies/ruby-2.7.0/bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin
##[error]Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

I tried setting the same secrets at repo level and it works.

**Comment by clareliguori** [comment]
Hi @GaboFDC can you confirm what repository access policy is associated with the org secrets?  For example, for each org secret, you can grant access to all repositories, to only private repositories, or to a specified list of repositories.

**Comment by GaboFDC** [comment]
It was shared with specified list of repositories. I had shared with this and a couple more of repos.

I'll try to do a test with the other policies tomorow

**Comment by GaboFDC** [comment]
I just tested with all 3 policies.
"All repositories"
"Private repositories"
"Selected repositories" (Here I tested selecting only the desired repo)

In all cases, it failed. Not sure if this is on GitHub side, as maybe these secrets are accessed in some other way?

These org secrets were recently deployed, not sure if anyone else could also test it to confirm

**Comment by clareliguori** [comment]
I'm not aware of anything the action needs to do to access Organizational secrets. The individual actions just rely on the Actions framework to populate the secrets for them.

Have you tried testing with a generic echo? For example:
```
steps:
      - name: Dump secret
        env:
          MY_SECRET: ${{ secrets.MY_ORG_SECRET }}
        run: echo "$MY_SECRET"
```
If it's successful, you should see a masked value (e.g. `***`).  Secret values are supposed to be masked automatically, but try it with a secret that doesn't contain any sensitive info, just in case.
