### ISSUE TITLE
OIDC Not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by MaxOrelus** [aws-actions/configure-aws-credentials#690]
### Describe the bug

My organization recently wants to make the switch from access keys to role based github actions. I've made all the changes indicated in the documentation, but I'm having issues with OIDC.

### workflow.yaml

```yaml
on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build/Push Images
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<<account_id>>:role/github-actions-role
          aws-region: us-east-1

      - name: Validate
        run: |
          aws sts get-caller-identity
```

### AWS Identity Provider

I created an identity provider with the following information:

- **provider**: `token.actions.githubusercontent.com`
- **audience**: `sts.amazonaws.com`

### AWS IAM Role

I created a IAM role with "AdministratorAccess" permissions with the following trust policy:

#### Trust Policy

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<<account_id>>:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:org_name/repo_name:*"
                }
            }
        }
    ]
}
```

### Expected Behavior

Login using temporary credentials

### Error

```
(node:1666) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/[7](https://github.com/Alara-Imaging/supabase-kong/actions/runs/4378313896/jobs/7662898547#step:3:8)PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

```
Error: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

### Reproduction Steps

Follow the procedures indicated in "*Describe the bug*".

### Additional Information/Context

Any additional details I can provided, but I imagine the above should suffice.
