### ISSUE TITLE
role-chaining 

### ISSUE THREAD

**Issue by abdmabrouk** [aws-actions/configure-aws-credentials#734]
### Describe the issue

As per the Documentation, OIDC role can assume another role as following, 
```
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
        role-session-name: MySessionName
    - name: Configure other AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::987654321000:role/my-second-role
        role-session-name: MySessionName
        role-chaining: true
```

But when i run this code,  i got the follwoing warning, is that normal ?!!

Warning: Unexpected input(s) 'role-chaining', valid inputs are ['audience', 'aws-access-key-id', 'aws-secret-access-key', 'aws-session-token', 'aws-region', 'mask-aws-account-id', 'role-to-assume', 'web-identity-token-file', 'role-duration-seconds', 'role-session-name', 'role-external-id', 'role-skip-session-tagging', 'http-proxy']
