### ISSUE TITLE
From US account switch to CN account, Error: The security token included in the request is invalid

### ISSUE THREAD

**Issue by yanjiefan** [aws-actions/configure-aws-credentials#756]
### Describe the bug

First, login to my US account's role and do something
Then, login CN account's role

If just login CN account, or from US account switch to another US account, it can work

### Expected Behavior

It can login successful

### Current Behavior

Error: The security token included in the request is invalid

### Reproduction Steps

      - name: Configure AWS credentials US
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::111111111111:role/github-actions
          aws-region: us-west-2
      - run: Do something
      - name: Configure AWS credentials CN
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws-cn:iam::222222222222:role/github-actions
          aws-region: cn-north-1

**Comment by jack-slip** [comment]
https://github.com/aws-actions/configure-aws-credentials/issues/357

**Comment by jack-slip** [comment]
new thumbprint is f879abce0008e4eb126e0097e46620f5aaae26ad

**Comment by libc** [comment]
For whoever gets here for whatever reason.

`f879abce0008e4eb126e0097e46620f5aaae26ad` is not the correct thumbprint. It's the sha1 of te certificate, while you should be trusting thumbprints of the intermediate CA.

Please use thumbprints from https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/ not `f879abce0008e4eb126e0097e46620f5aaae26ad`

**Comment by jack-slip** [comment]
> For whoever gets here for whatever reason.
> 
> 
> 
> `f879abce0008e4eb126e0097e46620f5aaae26ad` is not the correct thumbprint. It's the sha1 of te certificate, while you should be trusting thumbprints of the intermediate CA.
> 
> 
> 
> Please use thumbprints from https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/ not `f879abce0008e4eb126e0097e46620f5aaae26ad`

Thanks for sharing that. 

`f879abce0008e4eb126e0097e46620f5aaae26ad` Was correct enough to get our ci/cd running but we'll switch to the recommended solution.

**Comment by peterwoodworth** [comment]
It seems that the comments in this thread should be going to #357, please make sure you're in the right thread :) 

@yanjiefan there might be an issue with the environment variables not clearing between runs, try clearing out your AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN environment variables in a step between assuming these roles, and let me know if that works.

**Comment by yanjiefan** [comment]
> It seems that the comments in this thread should be going to #357, please make sure you're in the right thread :)
> 
> @yanjiefan there might be an issue with the environment variables not clearing between runs, try clearing out your AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN environment variables in a step between assuming these roles, and let me know if that works.

It can work ☺ (clear the environment variables), the code is:
```
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::111111111111:role/github-actions
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Configure AWS credentials CN
        uses: aws-actions/configure-aws-credentials@v2
        env:
          AWS_ACCESS_KEY_ID: ""
          AWS_SECRET_ACCESS_KEY: ""
          AWS_SESSION_TOKEN: ""
        with:
          role-to-assume: arn:aws-cn:iam::222222222222:role/github-actions
          aws-region: cn-north-1
      - name: Login to Amazon ECR
        id: login-ecr-cn
        uses: aws-actions/amazon-ecr-login@v1
```
