### ISSUE TITLE
potential vulnerability, secrets are left in env.

### ISSUE THREAD

**Issue by Borda** [aws-actions/configure-aws-credentials#766]
### Describe the bug

After calling this action seems like all credentials are left vulnerable in env. variables:
```
  aws s3 sync ...
  shell: bash --noprofile --norc -e -o pipefail {0}
  env:
    FREEZE_REQUIREMENTS: 1
    TORCH_URL: https://download.pytorch.org/whl/cpu/torch_stable.html
    PYPI_CACHE_DIR: _pip-wheels
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
```

### Expected Behavior

credentials stay secret without leaking

### Current Behavior

credentials if used in GH action under `pull_request_target` could be exploited

### Reproduction Steps

https://github.com/Lightning-AI/lightning/actions/runs/5507466178/jobs/10037458558?pr=18042
