### ISSUE TITLE
Clarify Open ID Connect in AWS documentation

### ISSUE THREAD

**Issue by iainelder** [aws-actions/configure-aws-credentials#776]
### Describe the issue

Today is my first time working with OIDC to deploy to AWS from GitHub. I ran into #672. It was closed without a clear repro, so I thought I should explain how I got here.

I had followed the [OpenID Connect in AWS](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) documentation and then later I added an environment to my workflow.

I adapted the example trust policy:

```json
"Condition": {
  "StringEquals": {
    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
  }
}
```

That policy works until I add an environment to my workflow. Then it mysteriously fails, as documented in #672.

I wish I had read this repo's README full first.

Compare the policy above to the one in this repo's README:

```yaml
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
```

The README goes on to say:

> The subject can be scoped to a GitHub organization and repository as shown in the CloudFormation template. Additional claim conditions can be added for higher specificity as explained in the [GitHub documentation](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect).

I think the policy in the README is better for first time users because it locks down the `sub` to a specific repo without later creating any surprising conflicts because of changes to branch names, environment names, or whatever else may cause GitHub to change the `sub` value.

So, could you reword that other documentation to include that information that helped a first-timer?
