### ISSUE TITLE
UnrecognizedClientException: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by gayatribrg** [aws-actions/configure-aws-credentials#788]
### Describe the bug

I am using aws-actions/configure-aws-credentials@v2 to assume a role and I realize the temporary credentials generated as part of env can be used in the next step.

```
 - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ steps.assume-role.outputs.role }}
          aws-region: somevalue
          role-session-name: samplerolesession
          role-duration-seconds: 1200
		  
 - name: connect to ssm

        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          working-directory: /tmp
          command: ls -a
          comment: Sample script
```		  
However on step 2 I get the error "UnrecognizedClientException: The security token included in the request is invalid.
code: 'UnrecognizedClientException'"

### Expected Behavior

Tempoarary credentials should be successfully used in next steps.

### Current Behavior

I get the error "UnrecognizedClientException: The security token included in the request is invalid.
code: 'UnrecognizedClientException'"

### Reproduction Steps

Call both these actions and kindly let me know what is being missed.

**Comment by peterwoodworth** [comment]
What happens when you run `get-caller-identity`? Does the role you expect return? And be sure to check that the role you expect to be assumed is in fact the role being passed in to your workflow

```
 - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ steps.assume-role.outputs.role }}
          aws-region: somevalue
          role-session-name: samplerolesession
          role-duration-seconds: 1200
		  
   - name: get caller identity
      run: |
        aws sts get-caller-identity
```
