### ISSUE TITLE
V3 breaks by somehow assuming the use of OIDC

### ISSUE THREAD

**Issue by Neurrone** [aws-actions/configure-aws-credentials#792]
### Describe the bug

The action fails and somehow assumes the use of OIDC, even though it wasn't being used / configured.

### Expected Behavior

No breakage when updating to V3

### Current Behavior

Action fails with the following error:

```
It looks like you might be trying to authenticate with OIDC. Did you mean to set the `id-token` permission?
Error: Could not determine how to assume credentials. Please check your inputs and try again.
```

### Reproduction Steps

```
    - name: Assume deployment role
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.DEPLOYER_ROLE_ARN }}
        role-skip-session-tagging: true
        role-duration-seconds: 1800
        role-external-id: ${{ env._EXTERNAL_ID }}
```
