### ISSUE TITLE
Credentials could not be loaded after migrate to v4

### ISSUE THREAD

**Issue by myshon** [aws-actions/configure-aws-credentials#850]
### Describe the bug

I use following credentials configuration (github workflows)
```
name: Pull request

on:
  pull_request:
    branches:
      - main
...
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
...
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
          aws-region: us-east-1
          mask-aws-account-id: false
```

It had worked, but recently `v2` suddenly stopped working with the following error ❌
```
Run aws-actions/configure-aws-credentials@v2
(node:2260) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any provider
```

I migrated to `v4` but another error occurred. ❌ 
```
Run aws-actions/configure-aws-credentials@v4
  with:
    role-skip-session-tagging: true
    role-duration-seconds: 900
    aws-region: us-east-1
    mask-aws-account-id: false
    audience: sts.amazonaws.com
...

Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```
I reverted to `v3` and it works ✅

### Expected Behavior

Success - credentials configured correctly ✅ 

### Current Behavior

```
Run aws-actions/configure-aws-credentials@v4
  with:
    role-skip-session-tagging: true
    role-duration-seconds: 900
    aws-region: us-east-1
    mask-aws-account-id: false
    audience: sts.amazonaws.com


Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

### Reproduction Steps

github workflow step invoked on dependabot pull-request
```
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
...
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
          aws-region: us-east-1
          mask-aws-account-id: false
```
