### ISSUE TITLE
Optionally output AWS temporary credentials

### ISSUE THREAD

**Issue by valentindeaconu** [aws-actions/configure-aws-credentials#859]
### Describe the feature

The action should support optionally exporting temporary AWS credentials to the output, so the job that is running the action can export them from the step output to the job output. In this way, we can collect them and pass them to a service container that is running for a subsequent job.

### Use Case

We want to run our tests in GitHub Actions pipeline and we have a Docker image that provisions a temporary database. The database needs to be restored from a backup that is currently uploaded in a private S3 bucket. We run the database in a Docker [service container](https://docs.github.com/en/actions/using-containerized-services/about-service-containers) and because we need to access the S3 bucket, we have to provide a set of AWS credentials. As we don't want to inject permanent credentials inside the image at build time, the only left solution would be to inject them at runtime from the container environment. In this case, we have two possible solutions: store a pair of permanent credentials in GA repository secrets and inject them at runtime OR generate a pair of temporary credentials by assuming a role in a previous job, then output the credentials from the job and fulfill them in the container environment.

Example configuration:
```
# ...

jobs:
  login-to-amazon:
    name: Authenticate in AWS
    steps:
      - name: Assume Backup Role
        id: backup-role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: 'eu-west-1'
          role-to-assume: 'arn:aws:iam::[ACCOUNT-ID]:role/[ROLE-NAME]'
          role-skip-session-tagging: true
          role-session-name: 'database-backup-e2e-tests'
          role-duration-seconds: 3600
    outputs:
      access_key_id: ${{ steps.backup-role.outputs.access_key_id }}
      secret_access_key: ${{ steps.backup-role.outputs.secret_access_key }}
      session_token: ${{ steps.backup-role.outputs.session_token }}
  run-tests:
    name: Run Tests
    needs: [login-to-amazon]
    services:
      db:
        # ...
        env:
          AWS_ACCESS_KEY_ID: ${{ needs.login-to-amazon.outputs.access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ needs.login-to-amazon.outputs.secret_access_key }}
          AWS_SESSION_TOKEN: ${{ needs.login-to-amazon.outputs.session_token }}
          # ...
```

### Proposed Solution

Add an opt-in flag that sets the credentials to the output (e.g. `output-temporary-credentials`). The flag should be marked with a warning that should inform the user that this is a security vulnerability and should be used with caution, similar to what the [amazon-ecr-login](https://github.com/aws-actions/amazon-ecr-login#docker-credentials) action does.

In this case (assuming a role and generating a pair of temporary credentials), the security risk of leaking credentials in GA logs is reduced as the credentials are set to expire in a given amount of time.

### Other Information

As described above, for our use case only, there are some workarounds:
- Injecting permanent credentials from the GitHub Actions Repository Secrets store;
- Bake in a set of permanent credentials inside the Docker image;
- Change the image to only accept a link from where the file is to be downloaded, then generate a pre-sign URL in a previous job and only export the pre-signed URL from that particular job.

The first two "solutions" come with the disadvantage of being somewhat hard to rotate the credentials when needed; the third one would require a lot of effort in our case as we use the same image on multiple CI pipelines.

After having a look at the codebase, it looks like the action was built to export those credentials initially, but then the flag never made its way to the action input:
https://github.com/aws-actions/configure-aws-credentials/blob/fbaaea849082b09c6da098c397edb77cf7d2875a/src/helpers.ts#L31-L41
To implement this feature, all we need to do is to connect an input flag to the `outputCredentials` parameter of the `exportCredentials` helper method, and if this flag is set, output a warning message.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Thanks for the time to submit this feature request,

We do have the `output-credentials` prop, and we have this documented in our README up at the top and also with [an example](https://github.com/aws-actions/configure-aws-credentials#retrieving-credentials-from-step-output-assumerole-with-temporary-credentials). This doesn't need any security warning, the security warning you linked is regarding masking your password 🙂

**Comment by valentindeaconu** [comment]
Thank you for your response. For some reason, I completely missed that (even after looking in code). However, this is not completely fixing the issue in our case (passing them from the step output to the job output) because the credentials are still marked as secrets from the following code:

https://github.com/aws-actions/configure-aws-credentials/blob/fbaaea849082b09c6da098c397edb77cf7d2875a/src/helpers.ts#L13-L29

And, because they're marked as secrets, we are not allowed to output them from the job (check the example configuration in the initial message):

```
run-tests / Authenticate in AWS Skip output 'access_key_id' since it may contain secret.
run-tests / Authenticate in AWS Skip output 'secret_access_key' since it may contain secret.
run-tests / Authenticate in AWS Skip output 'session_token' since it may contain secret.
```

I think, in this case, we will need one more flag that allows the user to skip the `core.setSecret` call.

**Comment by Blacknight1260** [comment]
How am I supposed to go to aws when I don’t know what the hell this is??’ I
contacted Amazon they said I didn’t use buy this service yet my life had
been a living hell with my wife walked out ready to divorce me wtf ??’
Changed google accounts so many times changed phone numbers bought new
computer   I need to hear these so called projects ??’ Amazon couldn’t
help??

**Comment by peterwoodworth** [comment]
> I think, in this case, we will need one more flag that allows the user to skip the core.setSecret call.

I don't comfortable introducing this as an option, but if you need this and feel confident in a secure implementation and usage of this, there's nothing stopping you from using your own fork with this change implemented 🙂

**Comment by valentindeaconu** [comment]
> I don't comfortable introducing this as an option

I understand your concern, that's why I suggested adding it as an opt-in feature, with a warning message that indicates this might be a security vulnerability (similar to what the ecr-login action does about the docker-password).

> there's nothing stopping you from using your own fork with this change implemented

There's no need to fork this project and invest in keeping it up-to-date as doing this manually with `aws-cli` and `jq` is pretty easy (see the spoiler below), but it feels like reinventing the wheel since this action is already here and it only needs an extra flag which is disabled by default.
<details>
  <summary>Workaround with aws-cli and jq</summary>

  ```yaml
  jobs:
  login-to-amazon:
    name: Authenticate in AWS
    steps:
      - name: Install jq
        shell: bash
        run: |
          sudo curl -o /usr/bin/jq -LSsf https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          sudo chmod +x /usr/bin/jq

      - name: Assume Backup Role
        id: backup-role
        env:
          AWS_ROLE_ARN: 'arn:aws:iam::[ACCOUNT-ID]:role/[ROLE-NAME]'
          SESSION_NAME: 'backup-role'
          SESSION_DURATION_SECONDS: '900' # 15 mins
        run: |
          credentials="$(aws sts assume-role --role-arn "$AWS_ROLE_ARN" --role-session-name "$SESSION_NAME" --duration-seconds "$SESSION_DURATION_SECONDS" --output json)"

          access_key_id="$(echo $credentials | jq -r .Credentials.AccessKeyId)"
          secret_access_key="$(echo $credentials | jq -r .Credentials.SecretAccessKey)"
          session_token="$(echo $credentials | jq -r .Credentials.SessionToken)"

          echo "access_key_id=$access_key_id" >> $GITHUB_OUTPUT
          echo "secret_access_key=$secret_access_key" >> $GITHUB_OUTPUT
          echo "session_token=$session_token" >> $GITHUB_OUTPUT
    outputs:
      access_key_id: ${{ steps.backup-role.outputs.access_key_id }}
      secret_access_key: ${{ steps.backup-role.outputs.secret_access_key }}
      session_token: ${{ steps.backup-role.outputs.session_token }}
  ```

</details>
