### ISSUE TITLE
Unset current credentials only

### ISSUE THREAD

**Issue by cmcnicholas** [aws-actions/configure-aws-credentials#863]
### Describe the feature

I would like to remove credentials from my action explicitly so any future actions (not modified by me) don't assuming those credentials.

### Use Case

To avoid contamination with future pipeline modifications.

### Proposed Solution

```yml
      # start: terraform validate/plan
      - name: Set terraform aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_TF_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TF_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Terraform validate
        run: npx nx validate site-terraform

      - name: Terraform plan
        run: npx nx plan:ci site-terraform

      # stops the credentials being used outside of terraform validate/plan
      - name: Unset terraform aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          unset-current-credentials: true
      # end: terraform validate/plan
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change
