### ISSUE TITLE
Action give warning about long term credentials when using InstanceRole permissions on self-hosted runners

### ISSUE THREAD

**Issue by bplessis-swi** [aws-actions/configure-aws-credentials#885]
### Describe the bug

Hi,

We are using self-hosted runners within our AWS account, with InstanceRole level permissions that allow for AssumeRole to different deploy roles. There is no long-term AWS credentials, or at least not in the common sense.

> Warning: To avoid using long-term AWS credentials, please update your workflows to authenticate using OpenID Connect. See https://s12d.com/gha-oidc-aws for more information.

### Expected Behavior

No warning should show up

### Current Behavior

A warning pop-up for each call to configure-aws-credentials in our workflows

> Warning: To avoid using long-term AWS credentials, please update your workflows to authenticate using OpenID Connect. See https://s12d.com/gha-oidc-aws for more information.

### Reproduction Steps

Simply using configure-aws-credentials without any credentials

```
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/${{ inputs.role-name }}
        role-duration-seconds: ${{ inputs.aws-credential-timeout }}
```
