### ISSUE TITLE
Replacement options for actions/aws deprecation for S3 CLI usage

### ISSUE THREAD

**Issue by jamesmosier** [aws-actions/configure-aws-credentials#9]
Hi 👋 I just noticed the deprecation warning for `actions/aws/cli` ("This actions has been deprecated in favor of https://github.com/aws-actions.  This repo has been archived and will be made private on 12/31/2019") and wanted to ask about replacement steps.

Currently I have a workflow defined as:

```
- name: Upload S3
  uses: actions/aws/cli@master
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  with:
    args: s3 cp ./results/ s3://reports/results/ --recursive
```

I didn't see any other aws/cli Action within the aws-actions organization. Is there a way to call the s3 CLI from Actions now? 

Sorry if I didn't see the proper migration steps and thanks for the Action/project 🙏

**Comment by ScriptAutomate** [comment]
By the looks of it, you'd have to go longhand across a few steps since there isn't yet an equivalent (official) awscli install action. Something similar to this, maybe, with [pipx](https://pipxproject.github.io/pipx/):

```yaml
...
...
...
  - name: Set up Python
    uses: actions/setup-python@v1
    with:
      python-version: 3.7 # Or other version
  - name: Install awscli via pipx # Isolates dependencies
    run: |
      pip install --user pipx
      pipx install awscli
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  - name: Upload S3
    run: |
      aws s3 cp ./results/ s3://reports/results/ --recursive
```

**Comment by clareliguori** [comment]
The AWS CLI is pre-installed in the GitHub-hosted environments:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts

So for example, `runs-on: ubuntu-latest` will have AWS CLI version 1.16.299, and you can do the following (same as @ScriptAutomate's suggestion, just without installing the AWS CLI):
```
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  - name: Upload S3
    run: |
      aws s3 cp ./results/ s3://reports/results/ --recursive
```
