### ISSUE TITLE
GHA runner suddenly not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by davidristov** [aws-actions/configure-aws-credentials#900]
### Describe the bug

All workflows suddenly started failing on the `aws-actions/configure-aws-credentials` step with the following error:
`Not authorized to perform sts:AssumeRoleWithWebIdentity`

From the workflows history, we had everything running up until Wednesday last week (Oct 18) and started seeing the issue from Friday (Oct 20). In between there are no relevant configuration changes that affect these resources (IAM role, OIDC provider).

### Expected Behavior

IAM role gets assumed successfully by the GitHub Actions runner.

### Current Behavior

GitHub Actions runner is not authorized to assume the defined IAM role.

### Reproduction Steps

GitHub workflow:
```
name: Development deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: 'eu-central-1'

permissions:
  id-token: write
  contents: read

jobs:
  my-job:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.SUBMODULES_PAT }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ vars.GHA_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: DevSession
```
Both `vars.GHA_ROLE` and `env.AWS_REGION` have the correct values.

Trust policy on IAM role:
```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Principal": {
				"Federated": "arn:aws:iam::<AWS_ACCOUNT>:oidc-provider/token.actions.githubusercontent.com"
			},
			"Action": "sts:AssumeRoleWithWebIdentity",
			"Condition": {
				"StringEquals": {
					"token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
				},
				"ForAnyValue:StringLike": {
					"token.actions.githubusercontent.com:sub": [
						"repo:<GITHUB_ORG>/<GITHUB_REPO>:*",
						"repo:<GITHUB_ORG>/<GITHUB_REPO>:*",
						"repo:<GITHUB_ORG>/<GITHUB_REPO>:*"
					]
				}
			}
		}
	]
}
```

AWS OIDC provider URL: `https://token.actions.githubusercontent.com`
Audience: `sts.amazonaws.com`
Thumbprints: `6938fd4d98bab03faadb97b34396831e3780aea1`, `1c58a3a8518e8759bf075b76b750d4f2df264fcd`, `1b511abead59c6ce207077c0bf0e0043b1382612`
