### ISSUE TITLE
Support for EKS Pod Identities

### ISSUE THREAD

**Issue by jtschelling** [aws-actions/configure-aws-credentials#942]
### Describe the feature

When I try and use this github action to assume into a role that my pod has the permissions to assume into the action errors out with `Error: Credentials could not be loaded, please check your action inputs: 169.254.170.23 is not a valid container metadata service hostname`
 
 This github action does not currently support the pod identities feature tmk.

### Use Case

I have an EKS cluster that I run self-hosted runners in through the actions-runner-controller project. I want to use pod identities to simplify my IAM management.

### Proposed Solution

Use the `client-eks-auth` feature in the aws sdk https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-eks-auth/README.md

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by tim-finnigan** [comment]
Thanks for the feature request. Here is documentation on EKS Pod Identities for our reference: https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html. 

Others can 👍this issue to show support and comment to share use cases and additional info.

**Comment by jmbravo** [comment]
Probably related with https://github.com/aws/aws-sdk-js-v3/issues/5709 ?

I'm getting the same error.

Got the same error also in Atlantis pod but upgrading Terraform AWS provider fixed the issue

**Comment by yurii-kryvosheia** [comment]
@jmbravo the workaround is to use v2.2.0 🤷🏼‍♂️

**Comment by yurii-kryvosheia** [comment]
> > @jmbravo the workaround is to use v2.2.0 🤷🏼‍♂️
> 
> In which component?

In configure-aws-credentials action.

**Comment by gabordk** [comment]
> > > @jmbravo the workaround is to use v2.2.0 🤷🏼‍♂️
> > 
> > 
> > In which component?
> 
> In configure-aws-credentials action.

Hi @yurii-kryvosheia, would you mind giving a little bit more detailed description how did you managed to go around this issue? Thanks a lot.

**Comment by jmbravo** [comment]
> > > @jmbravo the workaround is to use v2.2.0 🤷🏼‍♂️
> 
> > 
> 
> > In which component?
> 
> 
> 
> In configure-aws-credentials action.

EKS Pod Identity doesn't work in any aws-credential version (that's the purpose of this issue), I still don't understand your point.

**Comment by yurii-kryvosheia** [comment]
> > > > @jmbravo the workaround is to use v2.2.0 🤷🏼‍♂️
> > > 
> > > 
> > > In which component?
> > 
> > 
> > In configure-aws-credentials action.
> 
> Hi @yurii-kryvosheia, would you mind giving a little bit more detailed description how did you managed to go around this issue? Thanks a lot.

I'm sorry, I didn't dig into this issue, I just rolled back to [v2.2.0](https://github.com/aws-actions/configure-aws-credentials/releases/tag/v2.2.0).

**Comment by bogdan-matei** [comment]
It seems that this has been fixed in https://github.com/aws/aws-sdk-js-v3/pull/5739 so the SDK version should be updated.

**Comment by eahangari-8x8** [comment]
Hi any update on this?

**Comment by zarko-a** [comment]
Using the latest commit also worked. would be great if this made into an official release so people don't stumble on the same problem.

```
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@97834a484a5ab3c40fa9e2eb40fcf8041105a573
        with:
          ....
```

**Comment by eahangari-8x8** [comment]
any update on this? for v4.1.0

**Comment by distributed-clouds** [comment]
Hi All, just found this issue: 
is there any way to use the assume-role with the pod identity, it is still thinks Im using IRSA when I set 
```
      with:
        role-to-assume:
```

Thanks for your help

**Comment by BeyondEvil** [comment]
If you're using Actions Runner Controller (ARC) and have EKS Pod Identity setup correctly with an IAM Role, Service Account and EKS Pod Identity Association, you don't have to do anything. The credentials are already loaded in the environment.

```yaml
name: AWS Resources

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  direct:
    runs-on: <name of your self-hosted runner>
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - run: aws sts get-caller-identity

  indirect:
    runs-on: <name of your self-hosted runner>
    container:
      image: amazon/aws-cli:latest
      env:
        AWS_CONTAINER_CREDENTIALS_FULL_URI: http://169.254.170.23/v1/credentials
        AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
      volumes:
        - /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token:/var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
    steps:
      - run: aws sts get-caller-identity
```

**Comment by BeyondEvil** [comment]
The issue I had was that I needed the EKS Pod Identity role to assume yet another role.

This was the solution:

```yaml
name: Role chaining

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  assume-role:
    runs-on: <name of your self-hosted runner>
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: <role-to-assume-arn>
          role-chaining: true
          role-skip-session-tagging: true # It failed for me without this, not sure why
```

**Note** that it's _absolutely_ essential to have the `id-token` write permission.

**Comment by eepmoi** [comment]
I'm using EKS with https://github.com/actions/actions-runner-controller

This is how I got the cross account assume role working with EKS Pod Identity and `external-id` in case it helps others.

I was getting this error when using `external-id`:
```
Error: Could not assume role with user credentials: User: arn:aws:sts::012345678901:assumed-role/runner-role/abc-def-6d71de08-ed22-4e5b-8d9a-f708fd200f4c is not authorized to perform: sts:TagSession on resource: arn:aws:iam::012345678901:role/target-role
```

GHA workflow snippet.  Need to set `role-skip-session-tagging: true` otherwise you get this error:
```Error: Could not assume role with user credentials: Packed size of session tags consumes 119% of allotted space.```

```yaml
name: cross-account-external-id

on:
  workflow_dispatch:

permissions:
  id-token: write # required for aws-actions/configure-aws-credentials
  contents: read # required for actions/checkout

jobs:
  cross-account-external-id:
    runs-on:
      - my-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Assume cross account role
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::012345678901:role/target-role
          role-chaining: true
          role-external-id: target-role-external-id
          # without this setting get this error, suspect some bug with the configure-aws-credentials action
          # Error: Could not assume role with user credentials: Packed size of session tags consumes 119% of allotted space.
          role-skip-session-tagging: true
          aws-region: your-region
          retry-max-attempts: 3

      # for debugging
      # - name: Assume customer account role with aws cli
      #   run: |
      #     aws sts get-caller-identity
      #     aws sts assume-role \
      #       --role-arn arn:aws:iam::012345678901:role/target-role \
      #       --role-session-name cross-account-session \
      #       --external-id target-role-external-id
```

EKS account IAM role/policy snippet (terraform)
```hcl
resource "aws_iam_role" "runner_role" {
  name = "runner-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowEksAuthToAssumeRoleForPodIdentity"
        Effect = "Allow"
        Principal = {
          Service = "pods.eks.amazonaws.com"
        }
        Action = [
          "sts:AssumeRole",
          "sts:TagSession"
        ]
      }
    ]
  })
}

resource "aws_iam_role_policy" "runner_policy" {
  name = "runner-policy"
  role = aws_iam_role.runner_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowAssumeCrossAccountRole"
        Effect = "Allow"
        Action = [
          "sts:AssumeRole",
          "sts:TagSession"
        ]
        Resource = "arn:aws:iam::012345678901:role/target-role"
      }
    ]
  })
}
```

Target account IAM role/policy snippet (terraform).  The key here is that that you cannot combine `sts:AssumeRole` and `sts:TagSession` in the same trust policy statement as they conflict for some reason.  Setup similar to: https://docs.aws.amazon.com/eks/latest/userguide/pod-id-assign-target-role.html
```hcl
resource "aws_iam_role" "target_role" {
  name = "target-role"

  # cannot combine sts:AssumeRole and sts:TagSession in the same trust policy statement as they conflict for some reason
  # https://docs.aws.amazon.com/eks/latest/userguide/pod-id-assign-target-role.html
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::012345678901:root"
        }
        Action = "sts:AssumeRole"
        Condition = {
          StringEquals = {
            "sts:ExternalId" : "target-role-external-id"
          }
          ArnEquals = {
            "aws:PrincipalArn" : "arn:aws:iam::012345678901:role/runner-role"
          }
        }
      },
      {
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::012345678901:root"
        }
        Action = "sts:TagSession"
      }
    ]
  })
}
```
