### ISSUE TITLE
Error: Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by mattrw-wageloch** [aws-actions/configure-aws-credentials#961]
### Describe the bug

As of the 27th of December, 2023, our GitHub Actions workflow is unable to successfully assume the role with OIDC, with the error message **Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity**.

Our last successful execution of the workflow with the aws-actions/configure-aws-credentials@v4 action was approximately December 20th, 2023, however I cannot confirm when exactly this issue began occurring.

In trying to troubleshoot the issue, we have tried the following:
* Recreating the role and associated trust policy in AWS (both with the same name and different name)
* Replaced the roles to be assumed in our repository secrets with newly created ones
* Verified that our TrustPolicy is formatted correctly and contains the right details.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::ACCOUNTNUMBER:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:ORG/REPO:ref:refs/heads/testing"
                },
                "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

* Recreated the identity provider for GitHub to reobtain the thumbprint (no change in string)

The job in our workflow that uses the aws-actions/configure-aws-credentials@v4 is our deploy job.

```
  Deploy:
    # Deploys to a specific AWS S3 Bucket where AWS CodePipeline will pick up the changes and deploy automatically (if configured to do so).
    needs: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure Required AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TEST_AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Create Artifact Store
        shell: pwsh
        run: |
          $filepath = "${{ github.workspace }}/Builds/"
          if (-not (Test-Path $filepath)) {
            New-Item -Type Directory -Path $filepath
          }
      - name: Download Build Archive
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ${{ github.workspace }}/Builds/
      - name: Transfer Archive to AWS S3 Bucket
        shell: pwsh
        run: |
          Set-Location ${{ github.workspace }}/Builds/
           aws s3 cp BuildArchive.zip ${{ secrets.TEST_S3_BUCKET_AP }}
```

As noted above, beyond minor formatting or value changes, our working configuration remains unchanged. We have also looked for any possible notices by GitHub or AWS where there may have been a recent change that relates to the issue, but have not found anything.

### Expected Behavior

Authenticate correctly with the OICD as it has done previously in the past week or so.

### Current Behavior

When the action is run and gets to the aws-actions/configure-aws-credentials@v4, it attempts to run and loops through attempts until it fails, subsequently failing the job.

Run aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: ***
    aws-region: ap-southeast-2
    audience: sts.amazonaws.com
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Error: Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity

### Reproduction Steps

Have attempted to re-run the jobs with the minor alterations as noted above.
