### ISSUE TITLE
Deployment failed: Region not specified!

### ISSUE THREAD

**Issue by snehal-desh** [aws-actions/configure-aws-credentials#979]
### Describe the bug

When I try to deploy my code to Elastic beanstalk using github action it gives me "Deployment failed: Region not specified!" error.

### Expected Behavior

Action to run without a problem, if I set region.

### Current Behavior

My including a region named AWS_REGION, the action fails with the error:

Error: Deployment failed: Region not specified!

### Reproduction Steps

The workflow below creates two jobs, one of them works and the other fails:

```
name: customer information service

on: [push, pull_request]

env:
  AWS_REGION: eu-west-1
   

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
          name: artifact
          path: customer-information-webapp/target/customer-information-webapp.jar

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: eu-west-1
          #aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: false
          application_name: test_app
          environment_name: Testapp-env
          version_label: ${{github.SHA}}
          deployment_package: customer-information-webapp.jar
```

**Comment by tim-finnigan** [comment]
Thanks for reaching out. It looks like your region is commented out here: `# aws-region: eu-west-1`. I'd also check that you're meeting the requirements for https://github.com/einaregilsson/beanstalk-deploy/.

**Comment by snehal-desh** [comment]
Thanks reaching out to me, I also try the region without commented aws-region: eu-west-1 but I am still getting same error.
Also checked  https://github.com/einaregilsson/beanstalk-deploy/. but did not understand where the issue occurs.

**Comment by kellertk** [comment]
I edited your original comment to put your configuration in markdown format to make it easier to read. Your workflow syntax looks incorrect. You need to call `configure-aws-credentials` before you call `beanstalk-deploy`, otherwise `beanstalk-deploy` won't have any credentials to use. Try this:

```
      #Deploy the artifact (JAR) into AWS Beanstalk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          use_existing_version_if_available: false
          application_name: test_app
          environment_name: Testapp-env
          version_label: ${{github.SHA}}
          deployment_package: customer-information-webapp.jar
```
