### ISSUE TITLE
configure-aws-credentials@v4 fails to create ~/.aws/credentials file

### ISSUE THREAD

**Issue by ICeZer0** [aws-actions/configure-aws-credentials#987]
### Describe the bug

`aws-actions/configure-aws-credentials@v4` fails to create `~/.aws/credentials` within the GitHub actions workflow container. 

I discovered this bug while troubleshooting an issue with boto3 `botocore.exceptions.ProfileNotFound: The config profile (default) could not be found"`

      - name: Configure AWS Credentials v4
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

I double-checked this error by attempting to print the profile using `awk`

### Expected Behavior

This should create the following files `~/.aws/credentials` and `~/.aws/config`

### Current Behavior

No folder exists

### Reproduction Steps

# Create a github action with the following step
      - name: Configure AWS Credentials v4
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# Run the following command to check for the folder
      - name: Print aws profile names
        run: |
          awk -F '[][]' '/^\[/{print $2}' ~/.aws/credentials

Pipeline error: awk: fatal: cannot open file `/home/runner/.aws/credentials' for reading: No such file or directory

### Additional Information/Context

Using aws configure fixes this issue

      - name: Add profile credentials to ~/.aws/
        run: |
          pip install boto3
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
          aws configure set region us-west-2 --profile default

**Comment by tim-finnigan** [comment]
Hi @ICeZer0 thanks for reaching out. I think something like this captures what you're trying to do, can you confirm?

```yaml
on: push

jobs:
  auth-with-account:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials v4
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Add profile
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials  
              
      - name: Print aws profile names
        run: |
          awk -F '[][]' '/^\[/{print $2}' ~/.aws/credentials

      - name: Test credentials
        run: |
          aws s3 ls
```
